import type { DifferGateway } from "./application/gateway/differ";
import type { GithubGateway } from "./application/gateway/github";
import type { GithubAuthGateway } from "./application/gateway/github-auth";
import type { MessengerGateway } from "./application/gateway/messenger";
import type { TokenRepository } from "./domain/auth/token-repository";
import type { DiffRepository } from "./domain/diff/diff-repository";
import type { GuidRepository } from "./domain/guid/guid-repository";
import type { RepoIndexRepository } from "./domain/guid/repo-index-repository";
import { createChromeMessenger } from "./infrastructure/clients/chrome-messenger-client";
import { createQueue, type Queue } from "./infrastructure/clients/fetch-queue-client";
import { createQueuedFetch, GithubClient } from "./infrastructure/clients/github-client";
import { pollForToken, requestDeviceCode } from "./infrastructure/clients/github-device-flow-client";
import { createDiffer } from "./infrastructure/clients/wasm-differ-client";
import { createChromeDiffRepository } from "./infrastructure/repositories/chrome-diff-repository";
import { createChromeGuidRepository } from "./infrastructure/repositories/chrome-guid-repository";
import { createChromeRepoIndexRepository } from "./infrastructure/repositories/chrome-repo-index-repository";
import { createChromeTokenRepository } from "./infrastructure/repositories/chrome-token-repository";

export function createTokenStore(): TokenRepository {
  return createChromeTokenRepository(chrome.storage.local);
}

export function createMessenger(): MessengerGateway {
  return createChromeMessenger();
}

export function createDiffStore(): DiffRepository {
  return createChromeDiffRepository(chrome.storage.session);
}

export function createGuidCache(): GuidRepository {
  return createChromeGuidRepository(chrome.storage.local);
}

export function createRepoIndexStore(): RepoIndexRepository {
  return createChromeRepoIndexRepository(chrome.storage.local);
}

export function createGithubAuth(): GithubAuthGateway {
  return { requestDeviceCode, pollForToken };
}

export function createGithubClient(base: string, token: string, fetchFn: typeof fetch): GithubGateway {
  return new GithubClient(base, token, fetchFn);
}

export function createFetchQueue(concurrency: number): Queue {
  return createQueue(concurrency);
}

export function createGithubFetch(queue: Queue, lane: "user" | "prefetch"): typeof fetch {
  return createQueuedFetch(queue, lane === "user");
}

export function createDifferLoader(): () => Promise<DifferGateway> {
  let differ: Promise<DifferGateway> | undefined;
  return () => {
    // Lazy singleton; SW restart → re-fetch
    differ ??= fetch(chrome.runtime.getURL("prefablens.wasm"))
      .then((r) => r.arrayBuffer())
      .then(createDiffer);
    return differ;
  };
}

export async function createDemoDiffer(): Promise<DifferGateway> {
  const bytes = await createDemoFetchBytes()("prefablens.wasm");
  return createDiffer(bytes);
}

export function createFixtureGuidIndexLoader(): () => Promise<Map<string, string>> {
  // guid → asset path, generated by build.mjs from the fixture .meta files
  return async () => new Map(Object.entries(await (await fetch("fixtures/guids.json")).json()));
}

export function createDemoFetchBytes(): (url: string) => Promise<Uint8Array<ArrayBuffer>> {
  return async (url) => {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    return new Uint8Array(await res.arrayBuffer());
  };
}

export function createDemoFetchSource(): (side: "before" | "after", path: string) => Promise<Uint8Array> {
  const fetchBytes = createDemoFetchBytes();
  return (side, path) => fetchBytes(`fixtures/${side}/${path}`).catch(() => new Uint8Array());
}
