// Live demo for the site's extension.html: the mock PR page runs the
// extension's real renderer, toggle, and WASM diff engine, wired the same way
// as the content script minus the GitHub API and auth layers (never import
// anything that pulls github/client.ts — the demo has no GitHub instance to
// talk to and must stay free of that dependency). Living in the extension
// toolchain keeps the demo type-checked against the modules it uses;
// `node build.mjs --demo` bundles it as dist/demo.js for site/build.mjs.
// Diff inputs are fixture files served next to the page; site/build.mjs marks
// each Unity file header with data-before/data-after URLs (empty on the
// added/removed side, matching the CLI's empty-side semantics).
import { createToggle, injectPageStyles, type View } from "./content/toggle";
import { createViewState } from "./content/viewstate";
import { applyResolved } from "./github/resolved";
import { render, renderError, renderLoading } from "./renderer/render";
import type { DiffV2 } from "./types";
import { must } from "./util/must";
import { createDiffer, type Differ } from "./wasm/differ";

async function fetchBytes(url: string | undefined): Promise<Uint8Array<ArrayBuffer>> {
  if (!url) return new Uint8Array();
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

/** Diff with guid resolution, mirroring the extension's background handler:
 *  applyResolved attaches paths from the index, and the mergeSources loop
 *  fetches the source prefab of added/removed instances by resolved path and
 *  re-diffs with assets — here from fixture URLs instead of the GitHub API. */
async function diffResolved(
  differ: Differ,
  index: Map<string, string>,
  before: Uint8Array,
  after: Uint8Array,
): Promise<DiffV2> {
  let diff = applyResolved(differ.diff(before, after), index);
  const assets = new Map<string, Uint8Array>();
  for (let round = 0; round < 3; round++) {
    const needed = (diff.neededSources ?? []).filter((s) => !assets.has(s.guid));
    if (!needed.length) break;
    let progressed = false;
    for (const s of needed) {
      const path = diff.resolved?.[s.guid];
      if (path === undefined) continue;
      // A missing source degrades to the diff at this point, like the extension.
      const bytes = await fetchBytes(`fixtures/${s.side}/${path}`).catch(() => new Uint8Array());
      if (!bytes.length) continue;
      assets.set(s.guid, bytes);
      progressed = true;
    }
    if (!progressed) break;
    diff = applyResolved(differ.diffWithAssets(before, after, assets), index);
  }
  return diff;
}

function attachFile(
  header: HTMLElement,
  differ: Differ,
  index: Map<string, string>,
  initial: View,
): (view: View) => void {
  // Non-null: site/build.mjs always nests the header in a .file with a .js-file-content sibling.
  const content = must(header.parentElement?.querySelector<HTMLElement>(".js-file-content"));
  let host: HTMLDivElement | undefined;
  let root: ShadowRoot | undefined;
  let rendered = false;

  const show = (view: View): void => {
    if (view === "raw") {
      content.style.display = "";
      if (host) host.style.display = "none";
      return;
    }
    content.style.display = "none";
    if (!host || !root) {
      host = document.createElement("div");
      host.setAttribute("data-prefablens-view", "");
      // Same Primer class as .js-file-content: the collapse chevron toggles
      // Details--on on .file, and the host must opt into that CSS itself.
      host.classList.add("Details-content--hidden");
      root = host.attachShadow({ mode: "open" });
      content.after(host);
    }
    host.style.display = "";
    if (rendered) return; // fixtures are static: render each file once
    rendered = true;
    const target = root;
    renderLoading(target);
    Promise.all([fetchBytes(header.dataset.before), fetchBytes(header.dataset.after)])
      .then(([before, after]) => diffResolved(differ, index, before, after))
      .then((diff) => render(target, diff))
      .catch((err) => renderError(target, String(err)));
  };

  show(initial);
  return show;
}

async function main(): Promise<void> {
  injectPageStyles();

  // The collapse chevrons work on every file, Unity or not (GitHub behavior).
  for (const button of document.querySelectorAll(".file-collapse")) {
    button.addEventListener("click", () => {
      button.closest(".file")?.classList.toggle("Details--on");
      button.closest(".file")?.classList.toggle("open");
    });
  }

  const headers = [...document.querySelectorAll<HTMLElement>(".file-header[data-before]")];
  if (!headers.length) return;

  const differ = await createDiffer(await fetchBytes("prefablens.wasm"));
  // guid → asset path, generated by build.mjs from the fixture .meta files —
  // the demo's stand-in for the extension's GitHub-backed repo index.
  const index = new Map<string, string>(Object.entries(await (await fetch("fixtures/guids.json")).json()));
  // Semantic by default, like the extension once the user has picked it; the
  // demo has no chrome.storage, so persistence is a no-op.
  const state = createViewState("semantic", () => {});
  const appliers: Array<(view: View) => void> = [];
  state.onDefaultChange((view) => {
    for (const apply of appliers) apply(view);
  });

  // Global bar above the first Unity file, same anchor rule as the content script.
  const firstFile = must(headers[0]?.closest(".file"));
  const bar = document.createElement("div");
  bar.setAttribute("data-prefablens-global", "");
  const label = document.createElement("span");
  label.className = "prefablens-eyebrow";
  label.textContent = "PrefabLens";
  const globalToggle = createToggle((view) => state.setDefault(view), state.defaultView());
  bar.append(label, globalToggle.element);
  firstFile.before(bar);
  state.onDefaultChange((view) => globalToggle.set(view));

  for (const header of headers) {
    const path = header.dataset.path ?? "";
    const show = attachFile(header, differ, index, state.effective(path));
    const toggle = createToggle((view) => {
      state.setOverride(path, view); // a click overrides just this file
      show(view);
    }, state.effective(path));
    header.append(toggle.element);
    appliers.push((view) => {
      toggle.set(view);
      show(view);
    });
  }
}

void main();
