const std = @import("std");

const Pair = struct { id: u32, name: []const u8 };

// Unity classID の全マッピング(id 昇順)。
// 出典: Unity 6000.5 Manual "ClassID Reference"(343 エントリ)。
const table = [_]Pair{
    .{ .id = 0, .name = "Object" },
    .{ .id = 1, .name = "GameObject" },
    .{ .id = 2, .name = "Component" },
    .{ .id = 3, .name = "LevelGameManager" },
    .{ .id = 4, .name = "Transform" },
    .{ .id = 5, .name = "TimeManager" },
    .{ .id = 6, .name = "GlobalGameManager" },
    .{ .id = 8, .name = "Behaviour" },
    .{ .id = 9, .name = "GameManager" },
    .{ .id = 11, .name = "AudioManager" },
    .{ .id = 13, .name = "InputManager" },
    .{ .id = 18, .name = "EditorExtension" },
    .{ .id = 19, .name = "Physics2DSettings" },
    .{ .id = 20, .name = "Camera" },
    .{ .id = 21, .name = "Material" },
    .{ .id = 23, .name = "MeshRenderer" },
    .{ .id = 25, .name = "Renderer" },
    .{ .id = 27, .name = "Texture" },
    .{ .id = 28, .name = "Texture2D" },
    .{ .id = 29, .name = "OcclusionCullingSettings" },
    .{ .id = 30, .name = "GraphicsSettings" },
    .{ .id = 33, .name = "MeshFilter" },
    .{ .id = 41, .name = "OcclusionPortal" },
    .{ .id = 43, .name = "Mesh" },
    .{ .id = 45, .name = "Skybox" },
    .{ .id = 47, .name = "QualitySettings" },
    .{ .id = 48, .name = "Shader" },
    .{ .id = 49, .name = "TextAsset" },
    .{ .id = 50, .name = "Rigidbody2D" },
    .{ .id = 53, .name = "Collider2D" },
    .{ .id = 54, .name = "Rigidbody" },
    .{ .id = 55, .name = "PhysicsManager" },
    .{ .id = 56, .name = "Collider" },
    .{ .id = 57, .name = "Joint" },
    .{ .id = 58, .name = "CircleCollider2D" },
    .{ .id = 59, .name = "HingeJoint" },
    .{ .id = 60, .name = "PolygonCollider2D" },
    .{ .id = 61, .name = "BoxCollider2D" },
    .{ .id = 62, .name = "PhysicsMaterial2D" },
    .{ .id = 64, .name = "MeshCollider" },
    .{ .id = 65, .name = "BoxCollider" },
    .{ .id = 66, .name = "CompositeCollider2D" },
    .{ .id = 68, .name = "EdgeCollider2D" },
    .{ .id = 70, .name = "CapsuleCollider2D" },
    .{ .id = 72, .name = "ComputeShader" },
    .{ .id = 74, .name = "AnimationClip" },
    .{ .id = 75, .name = "ConstantForce" },
    .{ .id = 78, .name = "TagManager" },
    .{ .id = 81, .name = "AudioListener" },
    .{ .id = 82, .name = "AudioSource" },
    .{ .id = 83, .name = "AudioClip" },
    .{ .id = 84, .name = "RenderTexture" },
    .{ .id = 86, .name = "CustomRenderTexture" },
    .{ .id = 89, .name = "Cubemap" },
    .{ .id = 90, .name = "Avatar" },
    .{ .id = 91, .name = "AnimatorController" },
    .{ .id = 93, .name = "RuntimeAnimatorController" },
    .{ .id = 94, .name = "ShaderNameRegistry" },
    .{ .id = 95, .name = "Animator" },
    .{ .id = 96, .name = "TrailRenderer" },
    .{ .id = 98, .name = "DelayedCallManager" },
    .{ .id = 102, .name = "TextMesh" },
    .{ .id = 104, .name = "RenderSettings" },
    .{ .id = 108, .name = "Light" },
    .{ .id = 109, .name = "ShaderInclude" },
    .{ .id = 110, .name = "BaseAnimationTrack" },
    .{ .id = 111, .name = "Animation" },
    .{ .id = 114, .name = "MonoBehaviour" },
    .{ .id = 115, .name = "MonoScript" },
    .{ .id = 116, .name = "MonoManager" },
    .{ .id = 117, .name = "Texture3D" },
    .{ .id = 118, .name = "NewAnimationTrack" },
    .{ .id = 119, .name = "Projector" },
    .{ .id = 120, .name = "LineRenderer" },
    .{ .id = 121, .name = "Flare" },
    .{ .id = 122, .name = "Halo" },
    .{ .id = 123, .name = "LensFlare" },
    .{ .id = 124, .name = "FlareLayer" },
    .{ .id = 126, .name = "NavMeshProjectSettings" },
    .{ .id = 128, .name = "Font" },
    .{ .id = 129, .name = "PlayerSettings" },
    .{ .id = 130, .name = "NamedObject" },
    .{ .id = 134, .name = "PhysicsMaterial" },
    .{ .id = 135, .name = "SphereCollider" },
    .{ .id = 136, .name = "CapsuleCollider" },
    .{ .id = 137, .name = "SkinnedMeshRenderer" },
    .{ .id = 138, .name = "FixedJoint" },
    .{ .id = 141, .name = "BuildSettings" },
    .{ .id = 142, .name = "AssetBundle" },
    .{ .id = 143, .name = "CharacterController" },
    .{ .id = 144, .name = "CharacterJoint" },
    .{ .id = 145, .name = "SpringJoint" },
    .{ .id = 146, .name = "WheelCollider" },
    .{ .id = 147, .name = "ResourceManager" },
    .{ .id = 150, .name = "PreloadData" },
    .{ .id = 152, .name = "MovieTexture" },
    .{ .id = 153, .name = "ConfigurableJoint" },
    .{ .id = 154, .name = "TerrainCollider" },
    .{ .id = 156, .name = "TerrainData" },
    .{ .id = 157, .name = "LightmapSettings" },
    .{ .id = 158, .name = "WebCamTexture" },
    .{ .id = 159, .name = "EditorSettings" },
    .{ .id = 162, .name = "EditorUserSettings" },
    .{ .id = 164, .name = "AudioReverbFilter" },
    .{ .id = 165, .name = "AudioHighPassFilter" },
    .{ .id = 166, .name = "AudioChorusFilter" },
    .{ .id = 167, .name = "AudioReverbZone" },
    .{ .id = 168, .name = "AudioEchoFilter" },
    .{ .id = 169, .name = "AudioLowPassFilter" },
    .{ .id = 170, .name = "AudioDistortionFilter" },
    .{ .id = 171, .name = "SparseTexture" },
    .{ .id = 180, .name = "AudioBehaviour" },
    .{ .id = 181, .name = "AudioFilter" },
    .{ .id = 182, .name = "WindZone" },
    .{ .id = 183, .name = "Cloth" },
    .{ .id = 184, .name = "SubstanceArchive" },
    .{ .id = 185, .name = "ProceduralMaterial" },
    .{ .id = 186, .name = "ProceduralTexture" },
    .{ .id = 187, .name = "Texture2DArray" },
    .{ .id = 188, .name = "CubemapArray" },
    .{ .id = 191, .name = "OffMeshLink" },
    .{ .id = 192, .name = "OcclusionArea" },
    .{ .id = 193, .name = "Tree" },
    .{ .id = 195, .name = "NavMeshAgent" },
    .{ .id = 196, .name = "NavMeshSettings" },
    .{ .id = 198, .name = "ParticleSystem" },
    .{ .id = 199, .name = "ParticleSystemRenderer" },
    .{ .id = 200, .name = "ShaderVariantCollection" },
    .{ .id = 205, .name = "LODGroup" },
    .{ .id = 206, .name = "BlendTree" },
    .{ .id = 207, .name = "Motion" },
    .{ .id = 208, .name = "NavMeshObstacle" },
    .{ .id = 210, .name = "SortingGroup" },
    .{ .id = 212, .name = "SpriteRenderer" },
    .{ .id = 213, .name = "Sprite" },
    .{ .id = 214, .name = "CachedSpriteAtlas" },
    .{ .id = 215, .name = "ReflectionProbe" },
    .{ .id = 218, .name = "Terrain" },
    .{ .id = 220, .name = "LightProbeGroup" },
    .{ .id = 221, .name = "AnimatorOverrideController" },
    .{ .id = 222, .name = "CanvasRenderer" },
    .{ .id = 223, .name = "Canvas" },
    .{ .id = 224, .name = "RectTransform" },
    .{ .id = 225, .name = "CanvasGroup" },
    .{ .id = 226, .name = "BillboardAsset" },
    .{ .id = 227, .name = "BillboardRenderer" },
    .{ .id = 228, .name = "SpeedTreeWindAsset" },
    .{ .id = 229, .name = "AnchoredJoint2D" },
    .{ .id = 230, .name = "Joint2D" },
    .{ .id = 231, .name = "SpringJoint2D" },
    .{ .id = 232, .name = "DistanceJoint2D" },
    .{ .id = 233, .name = "HingeJoint2D" },
    .{ .id = 234, .name = "SliderJoint2D" },
    .{ .id = 235, .name = "WheelJoint2D" },
    .{ .id = 236, .name = "ClusterInputManager" },
    .{ .id = 237, .name = "BaseVideoTexture" },
    .{ .id = 238, .name = "NavMeshData" },
    .{ .id = 240, .name = "AudioMixer" },
    .{ .id = 241, .name = "AudioMixerController" },
    .{ .id = 243, .name = "AudioMixerGroupController" },
    .{ .id = 244, .name = "AudioMixerEffectController" },
    .{ .id = 245, .name = "AudioMixerSnapshotController" },
    .{ .id = 246, .name = "PhysicsUpdateBehaviour2D" },
    .{ .id = 247, .name = "ConstantForce2D" },
    .{ .id = 248, .name = "Effector2D" },
    .{ .id = 249, .name = "AreaEffector2D" },
    .{ .id = 250, .name = "PointEffector2D" },
    .{ .id = 251, .name = "PlatformEffector2D" },
    .{ .id = 252, .name = "SurfaceEffector2D" },
    .{ .id = 253, .name = "BuoyancyEffector2D" },
    .{ .id = 254, .name = "RelativeJoint2D" },
    .{ .id = 255, .name = "FixedJoint2D" },
    .{ .id = 256, .name = "FrictionJoint2D" },
    .{ .id = 257, .name = "TargetJoint2D" },
    .{ .id = 258, .name = "LightProbes" },
    .{ .id = 259, .name = "LightProbeProxyVolume" },
    .{ .id = 271, .name = "SampleClip" },
    .{ .id = 272, .name = "AudioMixerSnapshot" },
    .{ .id = 273, .name = "AudioMixerGroup" },
    .{ .id = 290, .name = "AssetBundleManifest" },
    .{ .id = 300, .name = "RuntimeInitializeOnLoadManager" },
    .{ .id = 310, .name = "UnityConnectSettings" },
    .{ .id = 319, .name = "AvatarMask" },
    .{ .id = 320, .name = "PlayableDirector" },
    .{ .id = 328, .name = "VideoPlayer" },
    .{ .id = 329, .name = "VideoClip" },
    .{ .id = 330, .name = "ParticleSystemForceField" },
    .{ .id = 331, .name = "SpriteMask" },
    .{ .id = 363, .name = "OcclusionCullingData" },
    .{ .id = 900, .name = "MarshallingTestObject" },
    .{ .id = 1001, .name = "PrefabInstance" },
    .{ .id = 1002, .name = "EditorExtensionImpl" },
    .{ .id = 1003, .name = "AssetImporter" },
    .{ .id = 1005, .name = "Mesh3DSImporter" },
    .{ .id = 1006, .name = "TextureImporter" },
    .{ .id = 1007, .name = "ShaderImporter" },
    .{ .id = 1008, .name = "ComputeShaderImporter" },
    .{ .id = 1020, .name = "AudioImporter" },
    .{ .id = 1026, .name = "HierarchyState" },
    .{ .id = 1028, .name = "AssetMetaData" },
    .{ .id = 1029, .name = "DefaultAsset" },
    .{ .id = 1030, .name = "DefaultImporter" },
    .{ .id = 1031, .name = "TextScriptImporter" },
    .{ .id = 1032, .name = "SceneAsset" },
    .{ .id = 1034, .name = "NativeFormatImporter" },
    .{ .id = 1035, .name = "MonoImporter" },
    .{ .id = 1038, .name = "LibraryAssetImporter" },
    .{ .id = 1040, .name = "ModelImporter" },
    .{ .id = 1041, .name = "FBXImporter" },
    .{ .id = 1042, .name = "TrueTypeFontImporter" },
    .{ .id = 1045, .name = "EditorBuildSettings" },
    .{ .id = 1048, .name = "InspectorExpandedState" },
    .{ .id = 1049, .name = "AnnotationManager" },
    .{ .id = 1050, .name = "PluginImporter" },
    .{ .id = 1051, .name = "EditorUserBuildSettings" },
    .{ .id = 1055, .name = "IHVImageFormatImporter" },
    .{ .id = 1101, .name = "AnimatorStateTransition" },
    .{ .id = 1102, .name = "AnimatorState" },
    .{ .id = 1105, .name = "HumanTemplate" },
    .{ .id = 1107, .name = "AnimatorStateMachine" },
    .{ .id = 1108, .name = "PreviewAnimationClip" },
    .{ .id = 1109, .name = "AnimatorTransition" },
    .{ .id = 1110, .name = "SpeedTreeImporter" },
    .{ .id = 1111, .name = "AnimatorTransitionBase" },
    .{ .id = 1112, .name = "SubstanceImporter" },
    .{ .id = 1113, .name = "LightmapParameters" },
    .{ .id = 1120, .name = "LightingDataAsset" },
    .{ .id = 1124, .name = "SketchUpImporter" },
    .{ .id = 1125, .name = "BuildReport" },
    .{ .id = 1126, .name = "PackedAssets" },
    .{ .id = 1127, .name = "VideoClipImporter" },
    .{ .id = 100000, .name = "int" },
    .{ .id = 100001, .name = "bool" },
    .{ .id = 100002, .name = "float" },
    .{ .id = 100003, .name = "MonoObject" },
    .{ .id = 100004, .name = "Collision" },
    .{ .id = 100005, .name = "Vector3f" },
    .{ .id = 100006, .name = "RootMotionData" },
    .{ .id = 100007, .name = "Collision2D" },
    .{ .id = 100008, .name = "AudioMixerLiveUpdateFloat" },
    .{ .id = 100009, .name = "AudioMixerLiveUpdateBool" },
    .{ .id = 100010, .name = "Polygon2D" },
    .{ .id = 100011, .name = "void" },
    .{ .id = 19719996, .name = "TilemapCollider2D" },
    .{ .id = 41386430, .name = "ImportLog" },
    .{ .id = 55640938, .name = "GraphicsStateCollection" },
    .{ .id = 73398921, .name = "VFXRenderer" },
    .{ .id = 156049354, .name = "Grid" },
    .{ .id = 156483287, .name = "ScenesUsingAssets" },
    .{ .id = 171741748, .name = "ArticulationBody" },
    .{ .id = 176606843, .name = "PhysicsCoreProjectSettings2D" },
    .{ .id = 181963792, .name = "Preset" },
    .{ .id = 209234237, .name = "ShaderIncludeReflection" },
    .{ .id = 285090594, .name = "IConstraint" },
    .{ .id = 294290339, .name = "AssemblyDefinitionReferenceImporter" },
    .{ .id = 330615474, .name = "ContentSummary" },
    .{ .id = 355983997, .name = "AudioResource" },
    .{ .id = 369655926, .name = "AssetImportInProgressProxy" },
    .{ .id = 382020655, .name = "PluginBuildInfo" },
    .{ .id = 382093023, .name = "UIAnimationBinder" },
    .{ .id = 387306366, .name = "MemorySettings" },
    .{ .id = 403037116, .name = "BuildMetaDataImporter" },
    .{ .id = 403037117, .name = "BuildInstructionImporter" },
    .{ .id = 426301858, .name = "EditorProjectAccess" },
    .{ .id = 468431735, .name = "PrefabImporter" },
    .{ .id = 483693784, .name = "TilemapRenderer" },
    .{ .id = 612988286, .name = "SpriteAtlasAsset" },
    .{ .id = 638013454, .name = "SpriteAtlasDatabase" },
    .{ .id = 641289076, .name = "AudioBuildInfo" },
    .{ .id = 644342135, .name = "CachedSpriteAtlasRuntimeData" },
    .{ .id = 655991488, .name = "MultiplayerManager" },
    .{ .id = 662584278, .name = "AssemblyDefinitionReferenceAsset" },
    .{ .id = 668709126, .name = "BuiltAssetBundleInfoSet" },
    .{ .id = 687078895, .name = "SpriteAtlas" },
    .{ .id = 687930938, .name = "BlobObject" },
    .{ .id = 702665669, .name = "DifferentMarshallingTestObject" },
    .{ .id = 747330370, .name = "RayTracingShaderImporter" },
    .{ .id = 815301076, .name = "PreviewImporter" },
    .{ .id = 825902497, .name = "RayTracingShader" },
    .{ .id = 850595691, .name = "LightingSettings" },
    .{ .id = 877146078, .name = "PlatformModuleSetup" },
    .{ .id = 890905787, .name = "VersionControlSettings" },
    .{ .id = 893571522, .name = "CustomCollider2D" },
    .{ .id = 895512359, .name = "AimConstraint" },
    .{ .id = 937362698, .name = "VFXManager" },
    .{ .id = 947337230, .name = "RoslynAnalyzerConfigAsset" },
    .{ .id = 954905827, .name = "RuleSetFileAsset" },
    .{ .id = 994735392, .name = "VisualEffectSubgraph" },
    .{ .id = 994735403, .name = "VisualEffectSubgraphOperator" },
    .{ .id = 994735404, .name = "VisualEffectSubgraphBlock" },
    .{ .id = 1001480554, .name = "Prefab" },
    .{ .id = 1027052791, .name = "LocalizationImporter" },
    .{ .id = 1096314112, .name = "BlockShaderSyntaxTree" },
    .{ .id = 1096314113, .name = "BlockShaderContainer" },
    .{ .id = 1096314114, .name = "BlockShaderErrors" },
    .{ .id = 1120581460, .name = "RenderAs2D" },
    .{ .id = 1149764431, .name = "BlockShaderSourceArtifact" },
    .{ .id = 1152215463, .name = "AssemblyDefinitionAsset" },
    .{ .id = 1154873562, .name = "SceneVisibilityState" },
    .{ .id = 1183024399, .name = "LookAtConstraint" },
    .{ .id = 1210832254, .name = "SpriteAtlasImporter" },
    .{ .id = 1223240404, .name = "MultiArtifactTestImporter" },
    .{ .id = 1233149941, .name = "AudioContainerElement" },
    .{ .id = 1268269756, .name = "GameObjectRecorder" },
    .{ .id = 1307931743, .name = "AudioRandomContainer" },
    .{ .id = 1325145578, .name = "LightingDataAssetParent" },
    .{ .id = 1386491679, .name = "PresetManager" },
    .{ .id = 1403656975, .name = "StreamingManager" },
    .{ .id = 1480428607, .name = "LowerResBlitTexture" },
    .{ .id = 1521398425, .name = "VideoBuildInfo" },
    .{ .id = 1542919678, .name = "StreamingController" },
    .{ .id = 1597193336, .name = "RoslynAdditionalFileAsset" },
    .{ .id = 1642787288, .name = "RoslynAdditionalFileImporter" },
    .{ .id = 1652712579, .name = "MultiplayerRolesData" },
    .{ .id = 1660057539, .name = "SceneRoots" },
    .{ .id = 1731078267, .name = "BrokenPrefabAsset" },
    .{ .id = 1736697216, .name = "AndroidAssetPackImporter" },
    .{ .id = 1740304944, .name = "VulkanDeviceFilterLists" },
    .{ .id = 1742807556, .name = "GridLayout" },
    .{ .id = 1766753193, .name = "AssemblyDefinitionImporter" },
    .{ .id = 1773428102, .name = "ParentConstraint" },
    .{ .id = 1777034230, .name = "RuleSetFileImporter" },
    .{ .id = 1798438448, .name = "D3D12DeviceFilterLists" },
    .{ .id = 1818360608, .name = "PositionConstraint" },
    .{ .id = 1818360609, .name = "RotationConstraint" },
    .{ .id = 1818360610, .name = "ScaleConstraint" },
    .{ .id = 1839735485, .name = "Tilemap" },
    .{ .id = 1896753125, .name = "PackageManifest" },
    .{ .id = 1896753126, .name = "PackageManifestImporter" },
    .{ .id = 1903396204, .name = "RoslynAnalyzerConfigImporter" },
    .{ .id = 1931382933, .name = "UIRenderer" },
    .{ .id = 1931382934, .name = "PanelRenderer" },
    .{ .id = 1953259897, .name = "TerrainLayer" },
    .{ .id = 1971053207, .name = "SpriteShapeRenderer" },
    .{ .id = 2058629509, .name = "VisualEffectAsset" },
    .{ .id = 2058629510, .name = "VisualEffectImporter" },
    .{ .id = 2058629511, .name = "VisualEffectResource" },
    .{ .id = 2059678085, .name = "VisualEffectObject" },
    .{ .id = 2083052967, .name = "VisualEffect" },
    .{ .id = 2083778819, .name = "LocalizationAsset" },
    .{ .id = 2089858483, .name = "ScriptedImporter" },
    .{ .id = 2097406814, .name = "BlockShaderImporter" },
    .{ .id = 2103361453, .name = "ShaderIncludeImporter" },
};

comptime {
    // 二分探索の前提: id 昇順・重複なし。崩れたらビルドで落とす。
    for (table[1..], 0..) |p, i| {
        if (p.id <= table[i].id) @compileError("classid table must be sorted by id and unique");
    }
}

pub fn typeName(class_id: u32) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const p = table[mid];
        if (p.id == class_id) return p.name;
        if (p.id < class_id) lo = mid + 1 else hi = mid;
    }
    return null;
}

test "classID lookup covers common types and returns null for unknown" {
    try std.testing.expectEqualStrings("GameObject", typeName(1).?);
    try std.testing.expectEqualStrings("Transform", typeName(4).?);
    try std.testing.expectEqualStrings("MonoBehaviour", typeName(114).?);
    try std.testing.expectEqualStrings("MeshRenderer", typeName(23).?);
    try std.testing.expectEqualStrings("RectTransform", typeName(224).?);
    try std.testing.expectEqualStrings("PrefabInstance", typeName(1001).?);
    try std.testing.expect(typeName(999999) == null);
}

test "classID lookup covers the full ClassIDReference table" {
    // Unity 6000.5 の ClassIDReference は 343 エントリ。境界(最小/最大 ID)と
    // 旧サブセットに無かった代表例で全域をおさえる。
    try std.testing.expectEqual(@as(usize, 343), table.len);
    try std.testing.expectEqualStrings("Object", typeName(0).?);
    try std.testing.expectEqualStrings("Rigidbody", typeName(54).?);
    try std.testing.expectEqualStrings("AnimatorState", typeName(1102).?);
    try std.testing.expectEqualStrings("Tilemap", typeName(1839735485).?);
    try std.testing.expectEqualStrings("ShaderIncludeImporter", typeName(2103361453).?);
}
