// Generated from Unity 6000.5.2f1 built-in resource files; do not edit by hand.
// Mirrors cli/src/builtin_refs.zig (see PrefabLens issue #104). The vitest
// parity test extension/src/renderer/builtin_refs.parity.test.ts keeps the
// Zig, TS and C# tables in sync.
using System.Collections.Generic;

namespace PrefabLens
{
    public static class BuiltinRefs
    {
        public const string DefaultResourcesGuid = "0000000000000000e000000000000000";
        public const string BuiltinExtraGuid = "0000000000000000f000000000000000";

        /// <summary>Object name for a reference into Unity's built-in resource files, or null when unknown.</summary>
        public static string Name(string guid, string fileId)
        {
            var table =
                guid == DefaultResourcesGuid ? DefaultResources
                : guid == BuiltinExtraGuid ? BuiltinExtra
                : null;
            return table != null && table.TryGetValue(fileId, out var n) ? n : null;
        }

        static readonly Dictionary<string, string> DefaultResources = new()
        {
            { "17", "Hidden/InternalErrorShader" },
            { "68", "Hidden/InternalClear" },
            { "69", "Hidden/Internal-Colored" },
            { "70", "Hidden/Internal-Loading" },
            { "300", "Internal-Skinning" },
            { "301", "Internal-BlendShape" },
            { "302", "Internal-RayTracing-AddInstancesIndirectSingleGeometry" },
            { "303", "Internal-RayTracing-AddInstancesIndirectMultiGeometry" },
            { "400", "Internal-VT-TranslationTableReplace" },
            { "401", "Internal-VT-TranslationTableUpsample" },
            { "600", "Internal-CreateFoveatedShadingRateTextureArray" },
            { "601", "Internal-CreateFoveatedShadingRateTextureNoArray" },
            { "602", "Internal-YFlipFoveatedShadingTexture" },
            { "10001", "Soft" },
            { "10100", "Font Material" },
            { "10101", "GUI/Text Shader" },
            { "10102", "LegacyRuntime" },
            { "10103", "Font Texture" },
            { "10200", "pSphere1" },
            { "10202", "Cube" },
            { "10203", "pCylinder1" },
            { "10204", "pPlane1" },
            { "10205", "polySurface2" },
            { "10206", "Cylinder" },
            { "10207", "Sphere" },
            { "10208", "Capsule" },
            { "10209", "Plane" },
            { "10210", "Quad" },
            { "10211", "Icosphere" },
            { "10212", "icosahedron" },
            { "10213", "pyramid" },
            { "10401", "EscToExit_back" },
            { "10402", "EscToExit_Text" },
            { "10406", "UnityWatermark-trial-big" },
            { "10407", "UnityWatermark-trial" },
            { "10409", "UnityWatermark-edu" },
            { "10410", "UnityWatermark-dev" },
            { "10411", "WarningSign" },
            { "10413", "UnityWatermark-proto" },
            { "10755", "Hidden/FrameDebuggerRenderTargetDisplay" },
            { "10756", "FrameDebuggerRenderTargetDisplay" },
            { "11000", "GameSkin" },
            { "11001", "box" },
            { "11002", "button active" },
            { "11003", "button hover" },
            { "11004", "button on hover" },
            { "11005", "button on" },
            { "11006", "button" },
            { "11007", "horizontal scrollbar thumb" },
            { "11008", "horizontal scrollbar" },
            { "11009", "horizontalslider" },
            { "11010", "slider thumb active" },
            { "11011", "slider thumb" },
            { "11012", "slidert humb hover" },
            { "11013", "toggle active" },
            { "11014", "toggle hover" },
            { "11015", "toggle on hover" },
            { "11016", "toggle on" },
            { "11017", "toggle on active" },
            { "11018", "toggle" },
            { "11019", "vertical scrollbar thumb" },
            { "11020", "vertical scrollbar" },
            { "11021", "verticalslider" },
            { "11022", "window on" },
            { "11023", "window" },
            { "11024", "textfield" },
            { "11025", "textfield on" },
            { "11026", "textfield hover" },
            { "11993", "TemplateAsset" },
            { "11995", "VisualTreeAsset" },
            { "11998", "StyleSheet" },
            { "12001", "GUISkin" },
            { "12002", "TerrainInspector" },
            { "12003", "ConsoleWindow" },
            { "12004", "ContainerWindow" },
            { "12005", "GUIView" },
            { "12006", "DockArea" },
            { "12007", "EditorWindow" },
            { "12008", "MainView" },
            { "12009", "PaneDragTab" },
            { "12010", "SplitView" },
            { "12011", "Toolbar" },
            { "12012", "Tools" },
            { "12013", "SceneView" },
            { "12014", "ProjectBrowser" },
            { "12015", "GameView" },
            { "12016", "PopupEditor" },
            { "12017", "ColorPicker" },
            { "12018", "AboutWindow" },
            { "12019", "InspectorWindow" },
            { "12020", "ShaderInspector" },
            { "12024", "AssetImporterEditor" },
            { "12025", "TextureImporterInspector" },
            { "12027", "TransformInspector" },
            { "12028", "ModelImporterEditor" },
            { "12029", "AudioImporterInspector" },
            { "12030", "TrueTypeFontImporterInspector" },
            { "12031", "TextureInspector" },
            { "12032", "GameObjectInspector" },
            { "12033", "MaterialEditor" },
            { "12034", "SaveWindowLayout" },
            { "12035", "DeleteWindowLayout" },
            { "12036", "RenderTextureInspector" },
            { "12038", "CubemapTextureInspector" },
            { "12039", "RagdollBuilder" },
            { "12040", "GenericInspector" },
            { "12041", "ProfilerIPWindow" },
            { "12042", "AppStatusBar" },
            { "12043", "BuildPlayerWindow" },
            { "12044", "PreferencesWindow" },
            { "12045", "Settings" },
            { "12046", "SnapSettings" },
            { "12047", "HostView" },
            { "12048", "TerrainWizard" },
            { "12049", "LightmapWizard" },
            { "12050", "ImportRawHeightmap" },
            { "12051", "ExportRawHeightmap" },
            { "12052", "SetResolutionWizard" },
            { "12053", "TreeWizard" },
            { "12054", "SplatWizard" },
            { "12055", "DetailMeshWizard" },
            { "12056", "DetailTextureWizard" },
            { "12057", "PlaceTreeWizard" },
            { "12058", "FlattenHeightmap" },
            { "12059", "FallbackEditorWindow" },
            { "12060", "MaximizedHostView" },
            { "12061", "SceneHierarchyWindow" },
            { "12062", "PackageExport" },
            { "12063", "PackageImport" },
            { "12064", "EyeDropper" },
            { "12066", "MonoScriptInspector" },
            { "12067", "AudioClipInspector" },
            { "12068", "ModelInspector" },
            { "12069", "TooltipView" },
            { "12070", "ProfilerWindow" },
            { "12071", "AnimationWindow" },
            { "12073", "AnimationEventPopup" },
            { "12074", "EditorSettingsInspector" },
            { "12076", "AnimationCleanupPopup" },
            { "12077", "ScriptReloadProperties" },
            { "12078", "MacroWindow" },
            { "12079", "LightingWindow" },
            { "12080", "AuxWindow" },
            { "12081", "ObjectSelector" },
            { "12082", "LabelCompletion" },
            { "12083", "CurveEditorWindow" },
            { "12084", "MonoScriptImporterInspector" },
            { "12086", "TextAssetInspector" },
            { "12087", "LightEditor" },
            { "12088", "AudioSourceInspector" },
            { "12089", "AudioLowPassFilterInspector" },
            { "12090", "OcclusionCullingWindow" },
            { "12091", "WebCamTextureInspector" },
            { "12092", "ShaderImporterInspector" },
            { "12093", "StandardShaderGUI" },
            { "12094", "LegacyIlluminShaderGUI" },
            { "12095", "GraphicsSettingsWindow" },
            { "12096", "PhysicsDebugWindow" },
            { "12097", "LightingExplorerWindow" },
            { "12098", "LightmapPreviewWindow" },
            { "12099", "AudioReverbZoneEditor" },
            { "12101", "ClothInspector" },
            { "12103", "PragmaFixingWindow" },
            { "12104", "WindInspector" },
            { "12105", "TreeEditor" },
            { "12106", "TreeData" },
            { "12107", "PlayerSettingsEditor" },
            { "12108", "EditorUpdateWindow" },
            { "12109", "AudioReverbFilterEditor" },
            { "12111", "AssetStoreWindow" },
            { "12112", "AssetStoreContext" },
            { "12113", "AssembleEditorSkin" },
            { "12114", "OcclusionAreaEditor" },
            { "12115", "CameraEditor" },
            { "12116", "WindowFocusState" },
            { "12117", "AndroidKeystoreWindow" },
            { "12118", "AudioDistortionFilterEditor" },
            { "12119", "AudioEchoFilterEditor" },
            { "12120", "AudioHighPassFilterEditor" },
            { "12121", "AudioChorusFilterEditor" },
            { "12122", "BoxColliderEditor" },
            { "12123", "SphereColliderEditor" },
            { "12124", "CapsuleColliderEditor" },
            { "12125", "MeshColliderEditor" },
            { "12126", "WheelColliderEditor" },
            { "12127", "RigidbodyEditor" },
            { "12128", "AssetSaveDialog" },
            { "12129", "AnnotationWindow" },
            { "12130", "IconSelector" },
            { "12131", "ScriptExecutionOrderInspector" },
            { "12132", "AnimationEditor" },
            { "12133", "SkinnedMeshRendererEditor" },
            { "12134", "PreviewWindow" },
            { "12135", "LODGroupEditor" },
            { "12136", "OffMeshLinkInspector" },
            { "12137", "ParticleSystemWindow" },
            { "12138", "ParticleSystemInspector" },
            { "12139", "MeshRendererEditor" },
            { "12140", "GradientPicker" },
            { "12141", "NavMeshEditorWindow" },
            { "12142", "FontInspector" },
            { "12143", "SpriteMaskEditor" },
            { "12146", "Brush" },
            { "12147", "BrushInspector" },
            { "12148", "TerrainLayerInspector" },
            { "12149", "TilemapRendererEditor" },
            { "12150", "SpriteRendererEditor" },
            { "12151", "SpriteInspector" },
            { "12152", "SpriteShapeRendererInspector" },
            { "12153", "TagManagerInspector" },
            { "12154", "RenderSettingsInspector" },
            { "12155", "ShaderVariantCollectionInspector" },
            { "12160", "AssemblyDefinitionImporterInspector" },
            { "12161", "AssemblyDefinitionAsset" },
            { "12162", "IHVImageFormatImporterInspector" },
            { "12163", "VideoClipImporterInspector" },
            { "12164", "SketchUpImporterEditor" },
            { "12165", "VideoClipImporterInspector/TargetSettings" },
            { "12166", "AudioImporterInspector/PlatformSettings" },
            { "12167", "ShaderImporterInspector/ShaderProperties" },
            { "12168", "AssemblyDefinitionReferenceImporterInspector/AssemblyDefinitionReferenceState" },
            { "12169", "AssemblyDefinitionImporterInspector/AssemblyDefinitionState" },
            { "12170", "AssemblyDefinitionReferenceImporterInspector" },
            { "12171", "AssemblyDefinitionReferenceAsset" },
            { "12172", "ComputeShaderImporterInspector" },
            { "12173", "TextScriptImporterEditor" },
            { "12203", "ProceduralTextureInspector" },
            { "12204", "NavMeshAgentInspector" },
            { "12205", "LightProbeGroupInspector" },
            { "12206", "LightProbeGroupSelection" },
            { "12207", "View" },
            { "12208", "OcclusionPortalInspector" },
            { "12209", "NavMeshObstacleInspector" },
            { "12210", "PopupList" },
            { "12211", "AssetStoreAssetInspector" },
            { "12212", "AssetStoreInstaBuyWindow" },
            { "12213", "AssetStoreLoginWindow" },
            { "12214", "LightProbesInspector" },
            { "12215", "AddComponentWindow" },
            { "12216", "EndNameEditAction" },
            { "12217", "DoCreateNoneAsset" },
            { "12218", "DoCreateNewAsset" },
            { "12219", "DoCreateFolder" },
            { "12220", "DoCreatePrefab" },
            { "12221", "DoCreateScriptAsset" },
            { "12222", "LicenseManagementWindow" },
            { "12223", "DoCreateAnimatorController" },
            { "12226", "LightmapParametersEditor" },
            { "12227", "DynamicCubemapEditor" },
            { "12300", "WindowResolve" },
            { "12301", "WindowChange" },
            { "12303", "WindowPending" },
            { "12304", "WindowRevert" },
            { "12306", "CharacterControllerEditor" },
            { "12307", "QualitySettingsEditor" },
            { "12308", "SavedSearchFilters" },
            { "12310", "TextMeshInspector" },
            { "12311", "Texture3DInspector" },
            { "12312", "MetroCreateTestCertificateWindow" },
            { "12313", "MetroCertificatePasswordWindow" },
            { "12314", "ModelImporterRigEditor" },
            { "12315", "ModelImporterModelEditor" },
            { "12316", "ModelImporterClipEditor" },
            { "12317", "ModelImporterMaterialEditor" },
            { "12318", "AvatarPreviewSelection" },
            { "12319", "PopupWindow" },
            { "12320", "PresetLibraryManager" },
            { "12321", "GradientPresetLibrary" },
            { "12322", "CurvePresetLibrary" },
            { "12323", "ColorPresetLibrary" },
            { "12324", "DoubleCurvePresetLibrary" },
            { "12325", "AtlasEditorWindow" },
            { "12326", "PackerWindow" },
            { "12327", "PolygonCollider2DEditor" },
            { "12328", "Physics2DPreferenceState" },
            { "12329", "Physics2DSettingsInspector" },
            { "12330", "GameViewSizes" },
            { "12331", "ColorPresetLibraryEditor" },
            { "12332", "GradientPresetLibraryEditor" },
            { "12333", "CurvePresetLibraryEditor" },
            { "12334", "DoubleCurvePresetLibraryEditor" },
            { "12335", "ReflectionProbeEditor" },
            { "12336", "LightProbeProxyVolumeEditor" },
            { "12337", "PrefabImporterEditor" },
            { "12346", "CustomCollider2DEditor" },
            { "12347", "CapsuleCollider2DEditor" },
            { "12348", "TargetJoint2DEditor" },
            { "12349", "RelativeJoint2DEditor" },
            { "12350", "BoxCollider2DEditor" },
            { "12351", "CircleCollider2DEditor" },
            { "12352", "EdgeCollider2DEditor" },
            { "12353", "AnchoredJoint2DEditor" },
            { "12354", "HingeJoint2DEditor" },
            { "12355", "SpringJoint2DEditor" },
            { "12356", "DistanceJoint2DEditor" },
            { "12357", "SliderJoint2DEditor" },
            { "12358", "WheelJoint2DEditor" },
            { "12359", "Effector2DEditor" },
            { "12360", "InterceptedEventsEditor" },
            { "12361", "RectTransformEditor" },
            { "12362", "SpriteEditorWindow" },
            { "12363", "SpriteAtlasInspector" },
            { "12364", "SpriteAtlasImporterInspector" },
            { "12365", "SpeedTreeImporterInspector" },
            { "12366", "SpeedTreeMaterialInspector" },
            { "12367", "BillboardRendererInspector" },
            { "12368", "BillboardAssetInspector" },
            { "12369", "SpeedTree8ShaderGUI" },
            { "12372", "AudioMixerEditor" },
            { "12373", "AudioMixerWindow" },
            { "12374", "AudioMixerGroupEditor" },
            { "12375", "AudioMixerControllerInspector" },
            { "12376", "AudioMixerSnapshotControllerInspector" },
            { "12377", "AudioContainerWindow" },
            { "12378", "AudioRandomContainerInspector" },
            { "12380", "Rigidbody2DEditor" },
            { "12381", "Joint2DEditor" },
            { "12382", "BuoyancyEffector2DEditor" },
            { "12383", "PlatformEffector2DEditor" },
            { "12384", "ScriptedImporterEditor" },
            { "12385", "StyleSheetImporter" },
            { "12386", "SerializableJsonDictionary" },
            { "12387", "StyleSheetImporterEditor" },
            { "12388", "ThemeStyleSheetImporter" },
            { "12389", "ThemeAssetDefinitionState" },
            { "12390", "ThemeStyleSheetImporterEditor" },
            { "12391", "GraphicsStateCollectionImporter" },
            { "12394", "GridEditor" },
            { "12395", "GridPalette" },
            { "12396", "Preset" },
            { "12397", "PresetEditor" },
            { "12398", "PresetManagerEditor" },
            { "12399", "PresetManager" },
            { "12400", "SceneSetEditor" },
            { "12401", "AssemblyDefinitionAsset" },
            { "12402", "ServicesEditorWindow" },
            { "12405", "SpeedTree9Importer" },
            { "12406", "SpeedTree9ImporterEditor" },
            { "12407", "SpeedTreeImporterOutputData" },
            { "12408", "SVGImporter" },
            { "12500", "GraphObject" },
            { "12501", "GraphObjectImp" },
            { "12502", "Holder" },
            { "12503", "UndoStateRecorder" },
            { "12504", "FieldWrapper" },
            { "12505", "GraphViewEditorWindow" },
            { "12506", "GraphViewEditorWindowImp" },
            { "12507", "ItemLibraryWindow" },
            { "12901", "AnimatorInspector" },
            { "12902", "AnimatorOverrideControllerInspector" },
            { "12905", "AnimationClipEditor" },
            { "12906", "AvatarEditor" },
            { "12907", "AnimatorTransitionInspector" },
            { "12908", "AnimatorStateTransitionInspector" },
            { "12914", "AnimatorControllerTool" },
            { "12915", "AvatarMaskInspector" },
            { "12916", "BlendTreeInspector" },
            { "12917", "AvatarMappingEditor" },
            { "12918", "AvatarMuscleEditor" },
            { "12919", "GraphGUI" },
            { "12920", "Graph" },
            { "12921", "Node" },
            { "12925", "PositionConstraintEditor" },
            { "12926", "RotationConstraintEditor" },
            { "12927", "ScaleConstraintEditor" },
            { "12928", "ParentConstraint" },
            { "12929", "AimConstraintEditor" },
            { "12930", "GraphGUI" },
            { "12931", "Graph" },
            { "12932", "StateNode" },
            { "12933", "AnyStateNode" },
            { "12934", "StateMachineNode" },
            { "12935", "StateEditor" },
            { "12936", "StateMachineInspector" },
            { "12937", "AnyStateNodeInspector" },
            { "12938", "EntryNodeInspector" },
            { "12939", "ExitNodeInspector" },
            { "12940", "StateMachineBehaviourEditor" },
            { "12941", "TimelineWindowViewPrefs" },
            { "13001", "EditorGameObjectCache" },
            { "13138", "Graph" },
            { "13139", "GraphInspector" },
            { "13140", "GraphGUI" },
            { "13141", "Node" },
            { "13202", "FrameDebuggerWindow" },
            { "13203", "PluginImporterInspector" },
            { "13205", "ParameterControllerEditor" },
            { "13312", "Tile" },
            { "13313", "TileBase" },
            { "13401", "TestRunnerWindow" },
            { "13501", "GUIViewDebuggerWindow" },
            { "13510", "VisualEffectInspector" },
            { "13601", "LookDevView" },
            { "13602", "LookDevConfig" },
            { "13603", "LookDevEnvironmentLibrary" },
            { "13604", "VideoPlayerEditor" },
            { "13800", "WebGLStrippingInfo" },
            { "13802", "StrippingInfo" },
            { "13803", "AndroidBuildProperties" },
            { "13804", "UIElementsViewImporter" },
            { "13805", "DefaultBuildProperties" },
            { "13806", "GraphViewUndoRedoSelection" },
            { "13807", "UIElementsSnippetAsset" },
            { "13852", "StreamingControllerEditor" },
            { "13853", "SettingsWindow" },
            { "13854", "ProjectSettingsWindow" },
            { "13855", "PreferenceSettingsWindow" },
            { "13856", "GraphViewMinimapWindow" },
            { "13857", "GraphViewBlackboardWindow" },
            { "13900", "AnimationWindowKeySelection" },
            { "13901", "AnimationWindowSelectionItem" },
            { "13902", "GameObjectSelectionItem" },
            { "13903", "AnimationClipSelectionItem" },
            { "13904", "CurveEditorSelection" },
            { "13951", "ShortcutManagerWindow" },
            { "13952", "PackageManifestImporterEditor" },
            { "13953", "PackageManagerWindow" },
            { "13954", "EditorSnapSettingsData" },
            { "13955", "ModeDescriptor" },
            { "13956", "UIElementsDebugger" },
            { "13957", "UIElementsEventsDebugger" },
            { "13958", "PackageManifestImporterEditor/PackageManifestState" },
            { "13959", "SnapSettingsWindow" },
            { "13960", "ProgressWindow" },
            { "13961", "PropertyEditor" },
            { "13962", "EditorToolbar" },
            { "13964", "PackageManagerProjectSettings" },
            { "13965", "EditorToolWindow" },
            { "13966", "SceneTemplateAsset" },
            { "13967", "SceneTemplateAssetInspectorWindow" },
            { "13968", "UIElementsSamples" },
            { "13969", "PanelSettingsInspector" },
            { "13970", "DeviceInfoImporterEditor" },
            { "13971", "DeviceInfoAssetEditor" },
            { "13972", "DeviceInfoAsset" },
            { "13973", "DeviceInfoImporter" },
            { "13974", "SimulatorWindow" },
            { "13975", "UIDocumentInspector" },
            { "13976", "UIRendererEditor" },
            { "13980", "SearchDatabase" },
            { "13981", "SearchDatabaseImporter" },
            { "13982", "SearchQueryAsset" },
            { "13984", "SearchWindow" },
            { "13986", "IndexManager" },
            { "13987", "MainToolbarWindow" },
            { "13988", "OverlayPreset" },
            { "13989", "OverlayPresetManager" },
            { "13990", "ManipulationToolCustomEditor" },
            { "13991", "SearchPickerWindow" },
            { "13993", "GameObjectToolContextCustomEditor" },
            { "13999", "Builder" },
            { "14000", "UndoHistoryWindow" },
            { "14001", "ParticleSystemForceFieldInspector" },
            { "14002", "HierarchyWindow" },
            { "14003", "AccessibilityHierarchyViewerWindow" },
            { "15000", "EditorTextSettings" },
            { "15001", "UILayoutDebuggerWindow" },
            { "15002", "AllocatorDebugger" },
            { "15003", "BuildProfile" },
            { "15004", "BuildProfileWindow" },
            { "15005", "BuildProfileContext" },
            { "15006", "PlatformDiscoveryWindow" },
            { "15007", "OverlayCanvasesData" },
            { "15008", "EditorToolsSettingsData" },
            { "15009", "BuildProfileGraphicsSettings" },
            { "15010", "BuildProfileQualitySettings" },
            { "15011", "GridSettings" },
            { "15012", "BuildAutomationSettings" },
            { "15020", "TopView" },
            { "15021", "DeployData" },
            { "15022", "MultiplayerRoleData" },
            { "15023", "MultiplayerRolesSettings" },
            { "15024", "OrchestratedScenario" },
            { "15025", "MultiplayerWindow" },
            { "15027", "OrchestratedScenarioUserSettings" },
            { "15050", "PlayModeUserSettings" },
            { "15051", "PlayModeScenariosWindow" },
            { "15052", "ActiveScenarioWindow" },
            { "15134", "BuilderInspectorPreviewWindow" },
            { "15135", "UIToolkitProjectSettings" },
            { "15136", "StyleSheetsWindow" },
            { "15800", "ContentDirectoryProfile" },
            { "19000", "TextSettings" },
            { "19001", "FontAsset" },
            { "19002", "SpriteAsset" },
            { "19003", "TextColorGradient" },
            { "19004", "TextStyleSheet" },
            { "19100", "VectorImage" },
            { "19101", "PanelSettings" },
            { "19102", "UIDocument" },
            { "19103", "PanelTextSettings" },
            { "19104", "UIRenderer" },
            { "19106", "PanelInputConfiguration" },
            { "19107", "FilterFunctionDefinition" },
            { "19202", "ThemeStyleSheet" },
            { "19300", "PhysicsLowLevelSettings2D" },
            { "19301", "PhysicsCoreSettings2D" },
            { "21000", "AdaptivePerformanceGeneralSettings" },
            { "21001", "AdaptivePerformanceManagerSettings" },
            { "21002", "AdaptivePerformanceLoader" },
            { "21003", "AdaptivePerformanceLoaderHelper" },
            { "21004", "AdaptivePerformanceManagerSpawner" },
            { "21005", "AdaptivePerformanceScaler" },
            { "21006", "IAdaptivePerformanceSettings" },
            { "21007", "BasicProviderLoader" },
            { "21008", "BasicProviderSettings" },
            { "21010", "AdaptivePerformanceGeneralSettingsPerBuildTarget" },
            { "21011", "SimulatorProviderLoader" },
            { "21012", "SimulatorProviderSettings" },
            { "21013", "BuildProfileProviderContainer" },
            { "21014", "Switch2PlayerSettings" },
            { "21015", "ProjectAuditorWindow" },
        };

        static readonly Dictionary<string, string> BuiltinExtra = new()
        {
            { "1", "Legacy Shaders/Diffuse Fast" },
            { "2", "Legacy Shaders/Bumped Diffuse" },
            { "3", "Legacy Shaders/Specular" },
            { "4", "Legacy Shaders/Bumped Specular" },
            { "5", "Legacy Shaders/Diffuse Detail" },
            { "6", "Legacy Shaders/VertexLit" },
            { "7", "Legacy Shaders/Diffuse" },
            { "8", "Legacy Shaders/Parallax Diffuse" },
            { "9", "Legacy Shaders/Parallax Specular" },
            { "10", "Legacy Shaders/Self-Illumin/Diffuse" },
            { "11", "Legacy Shaders/Self-Illumin/Bumped Diffuse" },
            { "12", "Legacy Shaders/Self-Illumin/Specular" },
            { "13", "Legacy Shaders/Self-Illumin/Bumped Specular" },
            { "14", "Legacy Shaders/Self-Illumin/VertexLit" },
            { "15", "Legacy Shaders/Self-Illumin/Parallax Diffuse" },
            { "16", "Legacy Shaders/Self-Illumin/Parallax Specular" },
            { "19", "Hidden/Internal-StencilWrite" },
            { "20", "Legacy Shaders/Reflective/Diffuse" },
            { "21", "Legacy Shaders/Reflective/Bumped Diffuse" },
            { "22", "Legacy Shaders/Reflective/Specular" },
            { "23", "Legacy Shaders/Reflective/Bumped Specular" },
            { "24", "Legacy Shaders/Reflective/VertexLit" },
            { "25", "Legacy Shaders/Reflective/Bumped Unlit" },
            { "26", "Legacy Shaders/Reflective/Bumped VertexLit" },
            { "27", "Legacy Shaders/Reflective/Parallax Diffuse" },
            { "28", "Legacy Shaders/Reflective/Parallax Specular" },
            { "30", "Legacy Shaders/Transparent/Diffuse" },
            { "31", "Legacy Shaders/Transparent/Bumped Diffuse" },
            { "32", "Legacy Shaders/Transparent/Specular" },
            { "33", "Legacy Shaders/Transparent/Bumped Specular" },
            { "34", "Legacy Shaders/Transparent/VertexLit" },
            { "35", "Legacy Shaders/Transparent/Parallax Diffuse" },
            { "36", "Legacy Shaders/Transparent/Parallax Specular" },
            { "40", "Legacy Shaders/Lightmapped/VertexLit" },
            { "41", "Legacy Shaders/Lightmapped/Diffuse" },
            { "42", "Legacy Shaders/Lightmapped/Bumped Diffuse" },
            { "43", "Legacy Shaders/Lightmapped/Specular" },
            { "44", "Legacy Shaders/Lightmapped/Bumped Specular" },
            { "45", "Standard (Specular setup)" },
            { "46", "Standard" },
            { "47", "Autodesk Interactive" },
            { "50", "Legacy Shaders/Transparent/Cutout/VertexLit" },
            { "51", "Legacy Shaders/Transparent/Cutout/Diffuse" },
            { "52", "Legacy Shaders/Transparent/Cutout/Bumped Diffuse" },
            { "53", "Legacy Shaders/Transparent/Cutout/Specular" },
            { "54", "Legacy Shaders/Transparent/Cutout/Bumped Specular" },
            { "62", "Hidden/Internal-DepthNormalsTexture" },
            { "64", "Hidden/Internal-ScreenSpaceShadows" },
            { "65", "Hidden/Internal-CombineDepthNormals" },
            { "66", "Hidden/BlitCopy" },
            { "67", "Hidden/BlitCopyDepth" },
            { "68", "Hidden/ConvertTexture" },
            { "69", "Hidden/Internal-DeferredShading" },
            { "74", "Hidden/Internal-DeferredReflections" },
            { "75", "Hidden/Internal-MotionVectors" },
            { "100", "Legacy Shaders/Decal" },
            { "101", "FX/Flare" },
            { "102", "Hidden/Internal-Flare" },
            { "103", "Skybox/Cubemap" },
            { "104", "Skybox/6 Sided" },
            { "105", "Hidden/Internal-Halo" },
            { "106", "Skybox/Procedural" },
            { "107", "Hidden/BlitCopyWithDepth" },
            { "108", "Skybox/Panoramic" },
            { "109", "Hidden/BlitToDepth" },
            { "110", "Hidden/BlitToDepth_MSAA" },
            { "111", "Hidden/BlitCopyHDRTonemap" },
            { "112", "Hidden/BlitCopyHDRTonemappedToHDRTonemap" },
            { "113", "Hidden/Internal-DebugPattern" },
            { "114", "Hidden/BlitCopyHDRTonemappedToSDR" },
            { "200", "Legacy Shaders/Particles/Additive" },
            { "201", "Legacy Shaders/Particles/~Additive-Multiply" },
            { "202", "Legacy Shaders/Particles/Additive (Soft)" },
            { "203", "Legacy Shaders/Particles/Alpha Blended" },
            { "205", "Legacy Shaders/Particles/Multiply" },
            { "206", "Legacy Shaders/Particles/Multiply (Double)" },
            { "207", "Legacy Shaders/Particles/Alpha Blended Premultiply" },
            { "208", "Legacy Shaders/Particles/VertexLit Blended" },
            { "209", "Legacy Shaders/Particles/Anim Alpha Blended" },
            { "210", "Particles/Standard Surface" },
            { "211", "Particles/Standard Unlit" },
            { "9000", "Hidden/Internal-GUITextureClip" },
            { "9001", "Hidden/Internal-GUITextureClipText" },
            { "9002", "Hidden/Internal-GUITexture" },
            { "9003", "Hidden/Internal-GUITextureBlit" },
            { "9004", "Hidden/Internal-GUIRoundedRect" },
            { "9007", "Hidden/Internal-GUIRoundedRectWithColorPerBorder" },
            { "9100", "Hidden/Internal-UIRDefault" },
            { "9101", "Hidden/Internal-UIRAtlasBlitCopy" },
            { "9105", "Hidden/Internal-UIE-ColorConversionBlit" },
            { "10300", "Default-Particle" },
            { "10301", "Default-Particle" },
            { "10302", "Default-Diffuse" },
            { "10303", "Default-Material" },
            { "10304", "Default-Skybox" },
            { "10305", "Default-Checker" },
            { "10306", "Default-Line" },
            { "10307", "Default-ParticleSystem" },
            { "10308", "Default-ParticleSystem" },
            { "10309", "Default-Checker-Gray" },
            { "10403", "UnitySplash-Light" },
            { "10404", "UnitySplash-Light" },
            { "10490", "Hidden/Nature/Terrain/Utilities" },
            { "10500", "Hidden/TerrainEngine/Details/Vertexlit" },
            { "10501", "Hidden/TerrainEngine/Details/WavingDoublePass" },
            { "10502", "Hidden/TerrainEngine/Details/BillboardWavingDoublePass" },
            { "10503", "Hidden/TerrainEngine/Splatmap/Diffuse-AddPass" },
            { "10504", "Hidden/TerrainEngine/Splatmap/Diffuse-Base" },
            { "10505", "Nature/Terrain/Diffuse" },
            { "10506", "Hidden/TerrainEngine/Splatmap/Diffuse-BaseGen" },
            { "10507", "Hidden/TerrainEngine/BillboardTree" },
            { "10508", "Hidden/Nature/Tree Soft Occlusion Bark Rendertex" },
            { "10509", "Nature/Tree Soft Occlusion Bark" },
            { "10510", "Hidden/Nature/Tree Soft Occlusion Leaves Rendertex" },
            { "10511", "Nature/Tree Soft Occlusion Leaves" },
            { "10512", "Legacy Shaders/Transparent/Cutout/Soft Edge Unlit" },
            { "10513", "Hidden/TerrainEngine/CameraFacingBillboardTree" },
            { "10600", "Nature/Tree Creator Bark" },
            { "10601", "Nature/Tree Creator Leaves" },
            { "10602", "Hidden/Nature/Tree Creator Bark Rendertex" },
            { "10603", "Hidden/Nature/Tree Creator Leaves Rendertex" },
            { "10604", "Hidden/Nature/Tree Creator Bark Optimized" },
            { "10605", "Hidden/Nature/Tree Creator Leaves Optimized" },
            { "10606", "Nature/Tree Creator Leaves Fast" },
            { "10607", "Hidden/Nature/Tree Creator Leaves Fast Optimized" },
            { "10608", "Hidden/Nature/Tree Creator Albedo Rendertex" },
            { "10609", "Hidden/Nature/Tree Creator Normal Rendertex" },
            { "10620", "Nature/Terrain/Specular" },
            { "10621", "Hidden/TerrainEngine/Splatmap/Specular-AddPass" },
            { "10622", "Hidden/TerrainEngine/Splatmap/Specular-Base" },
            { "10623", "Nature/Terrain/Standard" },
            { "10624", "Hidden/TerrainEngine/Splatmap/Standard-AddPass" },
            { "10625", "Hidden/TerrainEngine/Splatmap/Standard-Base" },
            { "10626", "Hidden/TerrainEngine/Splatmap/Standard-BaseGen" },
            { "10650", "Default-Terrain-Diffuse" },
            { "10651", "Default-Terrain-Specular" },
            { "10652", "Default-Terrain-Standard" },
            { "10700", "Mobile/Skybox" },
            { "10701", "Mobile/VertexLit" },
            { "10703", "Mobile/Diffuse" },
            { "10704", "Mobile/Bumped Diffuse" },
            { "10705", "Mobile/Bumped Specular" },
            { "10706", "Mobile/Bumped Specular (1 Directional Realtime Light)" },
            { "10707", "Mobile/VertexLit (Only Directional Lights)" },
            { "10708", "Mobile/Unlit (Supports Lightmap)" },
            { "10720", "Mobile/Particles/Additive" },
            { "10721", "Mobile/Particles/Alpha Blended" },
            { "10722", "Mobile/Particles/VertexLit Blended" },
            { "10723", "Mobile/Particles/Multiply" },
            { "10750", "Unlit/Transparent" },
            { "10751", "Unlit/Transparent Cutout" },
            { "10752", "Unlit/Texture" },
            { "10753", "Sprites/Default" },
            { "10754", "Sprites-Default" },
            { "10755", "Unlit/Color" },
            { "10757", "Sprites/Mask" },
            { "10758", "Sprites-Mask" },
            { "10760", "UI/Unlit/Transparent" },
            { "10761", "UI/Unlit/Detail" },
            { "10762", "UI/Unlit/Text" },
            { "10763", "UI/Unlit/Text Detail" },
            { "10764", "UI/Lit/Transparent" },
            { "10765", "UI/Lit/Bumped" },
            { "10766", "UI/Lit/Detail" },
            { "10767", "UI/Lit/Refraction" },
            { "10768", "UI/Lit/Refraction Detail" },
            { "10770", "UI/Default" },
            { "10782", "UI/Default Font" },
            { "10783", "UI/DefaultETC1" },
            { "10784", "Hidden/UI/CompositeOverdraw" },
            { "10785", "Hidden/UI/Overdraw" },
            { "10800", "Sprites/Diffuse" },
            { "10900", "Checkmark" },
            { "10901", "Checkmark" },
            { "10904", "UISprite" },
            { "10905", "UISprite" },
            { "10906", "Background" },
            { "10907", "Background" },
            { "10910", "InputFieldBackground" },
            { "10911", "InputFieldBackground" },
            { "10912", "Knob" },
            { "10913", "Knob" },
            { "10914", "DropdownArrow" },
            { "10915", "DropdownArrow" },
            { "10916", "UIMask" },
            { "10917", "UIMask" },
            { "13000", "Hidden/VisualizeShadingRateImage" },
            { "14000", "Nature/SpeedTree" },
            { "14001", "Nature/SpeedTree Billboard" },
            { "14002", "Nature/SpeedTree8" },
            { "14003", "Nature/SpeedTree9" },
            { "15100", "Hidden/GIDebug/TextureUV" },
            { "15101", "Hidden/GIDebug/ShowLightMask" },
            { "15102", "Hidden/GIDebug/UV1sAsPositions" },
            { "15103", "Hidden/GIDebug/VertexColors" },
            { "15104", "Hidden/CubeBlur" },
            { "15105", "Hidden/CubeCopy" },
            { "15106", "Hidden/CubeBlend" },
            { "15200", "Default-HighResolution" },
            { "15201", "Default-LowResolution" },
            { "15203", "Default-VeryLowResolution" },
            { "15204", "Default-Medium" },
            { "15300", "VR/SpatialMapping/Occlusion" },
            { "15301", "VR/SpatialMapping/Wireframe" },
            { "15302", "SpatialMappingOcclusion" },
            { "15303", "SpatialMappingWireframe" },
            { "15304", "Hidden/VR/BlitTexArraySlice" },
            { "15305", "Hidden/VR/Internal-VRDistortion" },
            { "15306", "Hidden/VR/BlitTexArraySliceToDepth" },
            { "15307", "Hidden/VR/BlitTexArraySliceToDepth_MSAA" },
            { "15308", "Hidden/Internal-ODSWorldTexture" },
            { "15309", "Hidden/Internal-CubemapToEquirect" },
            { "15312", "Hidden/VR/BlitFromTex2DToTexArraySlice" },
            { "15313", "Hidden/VR/BlitCopyHDRTonemapTexArraySlice" },
            { "15314", "Hidden/VR/BlitCopyHDRTonemappedToHDRTonemapTexArraySlice" },
            { "15315", "Hidden/VR/BlitCopyHDRTonemappedToSDRTexArraySlice" },
            { "16000", "Hidden/VideoComposite" },
            { "16001", "Hidden/VideoDecode" },
            { "16002", "Hidden/VideoDecodeOSX" },
            { "16003", "Hidden/VideoDecodeAndroid" },
            { "17000", "Hidden/Compositing" },
            { "18000", "Hidden/TerrainEngine/PaintHeight" },
            { "18001", "Hidden/TerrainEngine/HeightBlitCopy" },
            { "18002", "Hidden/TerrainEngine/GenerateNormalmap" },
            { "18003", "Hidden/TerrainEngine/TerrainLayerUtils" },
            { "18004", "Hidden/TerrainEngine/BrushPreview" },
            { "18005", "Hidden/TerrainEngine/CrossBlendNeighbors" },
            { "18006", "Hidden/TerrainEngine/TerrainBlitCopyZWrite" },
            { "19010", "Hidden/TextCore/Distance Field" },
            { "19011", "Hidden/TextCore/Distance Field SSD" },
            { "19012", "Hidden/TextCore/Sprite" },
            { "20000", "UnitySplash-Dark" },
            { "20001", "UnitySplash-Dark" },
            { "20100", "Invalidated" },
            { "20200", "Default-Skybox-Cubemap" },
            { "20201", "LightingData" },
            { "20204", "icudt73l" },
            { "20300", "Hidden/UIR/GaussianBlur" },
            { "20301", "Hidden/UIR/ColorEffect" },
            { "20400", "Hidden/VectorGraphics/Vector" },
            { "20401", "Hidden/VectorGraphics/VectorGradient" },
            { "20402", "Hidden/VectorGraphics/VectorBlendMax" },
            { "20403", "Hidden/VectorGraphics/VectorDemultiply" },
            { "20404", "Hidden/VectorGraphics/VectorExpandEdges" },
            { "20410", "Internal-VectorGraphics-Vector" },
            { "20411", "Internal-VectorGraphics-VectorGradient" },
            { "20500", "Hidden/Physics2D/SDF_CircleGeometry" },
            { "20501", "Hidden/Physics2D/SDF_CapsuleGeometry" },
            { "20502", "Hidden/Physics2D/SDF_PolygonGeometry" },
            { "20506", "Hidden/Physics2D/SDF_Line" },
            { "20507", "Hidden/Physics2D/SDF_Point" },
            { "20510", "SDF_CircleGeometry" },
            { "20511", "SDF_CapsuleGeometry" },
            { "20512", "SDF_PolygonGeometry" },
            { "20516", "SDF_Line" },
            { "20517", "SDF_Point" },
        };
    }
}
