import type { DifferPort } from "../application/port/differ";
import type { GithubPort } from "../application/port/github";
import type { GithubAuthPort } from "../application/port/github-auth";
import type { MessengerPort } from "../application/port/messenger";
import type { TokenRepository } from "../domain/auth/token-repository";
import type { DiffRepository } from "../domain/diff/diff-repository";
import type { GuidRepository } from "../domain/guid/guid-repository";
import type { RepoIndexRepository } from "../domain/guid/repo-index-repository";
import { createChromeMessenger } from "./providers/chrome-messenger";
import { createQueue, type Queue } from "./providers/fetch-queue";
import { createQueuedFetch, GithubClient } from "./providers/github-client";
import { pollForToken, requestDeviceCode } from "./providers/github-device-flow";
import { createDiffer } from "./providers/wasm-differ";
import { createChromeDiffRepository } from "./repositories/chrome-diff-repository";
import { createChromeGuidRepository } from "./repositories/chrome-guid-repository";
import { createChromeRepoIndexRepository } from "./repositories/chrome-repo-index-repository";
import { createChromeTokenRepository } from "./repositories/chrome-token-repository";

export function createTokenStore(): TokenRepository {
  return createChromeTokenRepository(chrome.storage.local);
}

export function createMessenger(): MessengerPort {
  return createChromeMessenger();
}

export function createDiffStore(): DiffRepository {
  return createChromeDiffRepository(chrome.storage.session);
}

export function createGuidCache(): GuidRepository {
  return createChromeGuidRepository(chrome.storage.local);
}

export function createRepoIndexStore(): RepoIndexRepository {
  return createChromeRepoIndexRepository(chrome.storage.local);
}

export function createGithubAuth(): GithubAuthPort {
  return { requestDeviceCode, pollForToken };
}

export function createGithubClient(base: string, token: string, fetchFn: typeof fetch): GithubPort {
  return new GithubClient(base, token, fetchFn);
}

export function createFetchQueue(concurrency: number): Queue {
  return createQueue(concurrency);
}

export function createGithubFetch(queue: Queue, lane: "user" | "prefetch"): typeof fetch {
  return createQueuedFetch(queue, lane === "user");
}

export function createDifferLoader(): () => Promise<DifferPort> {
  let differ: Promise<DifferPort> | undefined;
  return () => {
    // Lazy singleton; SW restart → re-fetch
    differ ??= fetch(chrome.runtime.getURL("prefablens.wasm"))
      .then((r) => r.arrayBuffer())
      .then(createDiffer);
    return differ;
  };
}

export async function createDemoDiffer(): Promise<DifferPort> {
  const bytes = await createDemoFetchBytes()("prefablens.wasm");
  return createDiffer(bytes);
}

export function createFixtureGuidIndexLoader(): () => Promise<Map<string, string>> {
  // guid → asset path, generated by build.mjs from the fixture .meta files
  return async () => new Map(Object.entries(await (await fetch("fixtures/guids.json")).json()));
}

export function createDemoFetchBytes(): (url: string) => Promise<Uint8Array<ArrayBuffer>> {
  return async (url) => {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    return new Uint8Array(await res.arrayBuffer());
  };
}

export function createDemoFetchSource(): (side: "before" | "after", path: string) => Promise<Uint8Array> {
  const fetchBytes = createDemoFetchBytes();
  return (side, path) => fetchBytes(`fixtures/${side}/${path}`).catch(() => new Uint8Array());
}
