import type { DiffCachePort } from "../application/port/diff-cache";
import type { DifferPort } from "../application/port/differ";
import type { GithubPort } from "../application/port/github";
import type { GithubAuthPort } from "../application/port/github-auth";
import type { GuidCachePort } from "../application/port/guid-cache";
import type { MessengerPort } from "../application/port/messenger";
import type { RepoIndexPort } from "../application/port/repo-index";
import type { TokenStorePort } from "../application/port/token-store";
import { createChromeMessenger } from "./providers/chrome-messenger";
import { createChromeTokenStore } from "./providers/chrome-token-store";
import { createQueue, type Queue } from "./providers/fetch-queue";
import { GithubClient } from "./providers/github-client";
import { pollForToken, requestDeviceCode } from "./providers/github-device-flow";
import { createDiffer } from "./providers/wasm-differ";
import { createMergeStore } from "./repositories/merge-store";
import { createSessionDiffStore } from "./repositories/session-diff-store";

export function createTokenStore(): TokenStorePort {
  return createChromeTokenStore(chrome.storage.local);
}

export function createMessenger(): MessengerPort {
  return createChromeMessenger();
}

export function createDiffStore(): DiffCachePort {
  return createSessionDiffStore(chrome.storage.session);
}

export function createGuidCache(): GuidCachePort {
  return createMergeStore(chrome.storage.local, "guids");
}

export function createRepoIndexStore(): RepoIndexPort {
  // Whole-repo .meta guid records for loadGuids/saveGuids
  const metaGuids = createMergeStore(chrome.storage.local, "metaGuids");
  return {
    loadGuids: (repo) => metaGuids.load(repo),
    saveGuids: (repo, entries) => metaGuids.save(repo, entries).catch(() => {}), // quota overflow → memory only
    async loadIndex(repo) {
      const key = `guidIndex:${repo}`;
      const stored = await chrome.storage.local.get([key]);
      return stored[key] as { treeSha: string; guids: Record<string, string> } | undefined;
    },
    async saveIndex(repo, index) {
      await chrome.storage.local.set({ [`guidIndex:${repo}`]: index }).catch(() => {});
    },
  };
}

export function createGithubAuth(): GithubAuthPort {
  return { requestDeviceCode, pollForToken };
}

export function createGithubClient(base: string, token: string, fetchFn: typeof fetch): GithubPort {
  return new GithubClient(base, token, fetchFn);
}

export function createFetchQueue(concurrency: number): Queue {
  return createQueue(concurrency);
}

export function createDifferLoader(): () => Promise<DifferPort> {
  let differ: Promise<DifferPort> | undefined;
  return () => {
    // Lazy singleton; SW restart → re-fetch
    differ ??= fetch(chrome.runtime.getURL("prefablens.wasm"))
      .then((r) => r.arrayBuffer())
      .then(createDiffer);
    return differ;
  };
}

export async function createDemoDiffer(): Promise<DifferPort> {
  const bytes = await createDemoFetchBytes()("prefablens.wasm");
  return createDiffer(bytes);
}

export async function loadFixtureGuidIndex(): Promise<Map<string, string>> {
  // guid → asset path, generated by build.mjs from the fixture .meta files
  return new Map(Object.entries(await (await fetch("fixtures/guids.json")).json()));
}

export function createDemoFetchBytes(): (url: string) => Promise<Uint8Array<ArrayBuffer>> {
  return async (url) => {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    return new Uint8Array(await res.arrayBuffer());
  };
}

export function createDemoFetchSource(): (side: "before" | "after", path: string) => Promise<Uint8Array> {
  const fetchBytes = createDemoFetchBytes();
  return (side, path) => fetchBytes(`fixtures/${side}/${path}`).catch(() => new Uint8Array());
}
