// Generated from Unity 6000.5.2f1 built-in resource files; do not edit by hand.
// Regenerate by running, in a Unity editor (batchmode is fine):
//   AssetDatabase.LoadAllAssetsAtPath(path) + TryGetGUIDAndLocalFileIdentifier
// over "Library/unity default resources" and "Resources/unity_builtin_extra",
// then feeding the (guid, fileID, name) dump through this file's generator
// (see PrefabLens issue #104). fileIDs are stable across Unity versions.

const std = @import("std");

pub const default_resources_guid = "0000000000000000e000000000000000";
pub const builtin_extra_guid = "0000000000000000f000000000000000";

const Entry = struct { file_id: i64, name: []const u8 };

/// True for references into Unity's two built-in resource files. These guids
/// never correspond to a .meta on disk, so resolution scans must neither
/// trigger on them nor wait for them.
pub fn isBuiltinGuid(guid: []const u8) bool {
    return std.mem.eql(u8, guid, default_resources_guid) or std.mem.eql(u8, guid, builtin_extra_guid);
}

test "isBuiltinGuid matches exactly the two built-in resource files" {
    try std.testing.expect(isBuiltinGuid(default_resources_guid));
    try std.testing.expect(isBuiltinGuid(builtin_extra_guid));
    try std.testing.expect(!isBuiltinGuid("d10cc984e47164feb9cb74c75c0f3cf6"));
}

/// Object name for a reference into Unity's built-in resource files, or null
/// when the guid is not one of the two built-in files or the fileID is unknown.
pub fn name(guid: []const u8, file_id: i64) ?[]const u8 {
    const table: []const Entry = if (std.mem.eql(u8, guid, default_resources_guid))
        &default_resources
    else if (std.mem.eql(u8, guid, builtin_extra_guid))
        &builtin_extra
    else
        return null;
    for (table) |e| {
        if (e.file_id == file_id) return e.name;
    }
    return null;
}

test "lookup names known built-ins and rejects everything else" {
    try std.testing.expectEqualStrings("Cube", name(default_resources_guid, 10202).?);
    try std.testing.expectEqualStrings("Default-Material", name(builtin_extra_guid, 10303).?);
    try std.testing.expect(name(default_resources_guid, 424242) == null);
    try std.testing.expect(name("abc123", 10202) == null);
}

const default_resources = [_]Entry{
    .{ .file_id = 17, .name = "Hidden/InternalErrorShader" },
    .{ .file_id = 68, .name = "Hidden/InternalClear" },
    .{ .file_id = 69, .name = "Hidden/Internal-Colored" },
    .{ .file_id = 70, .name = "Hidden/Internal-Loading" },
    .{ .file_id = 300, .name = "Internal-Skinning" },
    .{ .file_id = 301, .name = "Internal-BlendShape" },
    .{ .file_id = 302, .name = "Internal-RayTracing-AddInstancesIndirectSingleGeometry" },
    .{ .file_id = 303, .name = "Internal-RayTracing-AddInstancesIndirectMultiGeometry" },
    .{ .file_id = 400, .name = "Internal-VT-TranslationTableReplace" },
    .{ .file_id = 401, .name = "Internal-VT-TranslationTableUpsample" },
    .{ .file_id = 600, .name = "Internal-CreateFoveatedShadingRateTextureArray" },
    .{ .file_id = 601, .name = "Internal-CreateFoveatedShadingRateTextureNoArray" },
    .{ .file_id = 602, .name = "Internal-YFlipFoveatedShadingTexture" },
    .{ .file_id = 10001, .name = "Soft" },
    .{ .file_id = 10100, .name = "Font Material" },
    .{ .file_id = 10101, .name = "GUI/Text Shader" },
    .{ .file_id = 10102, .name = "LegacyRuntime" },
    .{ .file_id = 10103, .name = "Font Texture" },
    .{ .file_id = 10200, .name = "pSphere1" },
    .{ .file_id = 10202, .name = "Cube" },
    .{ .file_id = 10203, .name = "pCylinder1" },
    .{ .file_id = 10204, .name = "pPlane1" },
    .{ .file_id = 10205, .name = "polySurface2" },
    .{ .file_id = 10206, .name = "Cylinder" },
    .{ .file_id = 10207, .name = "Sphere" },
    .{ .file_id = 10208, .name = "Capsule" },
    .{ .file_id = 10209, .name = "Plane" },
    .{ .file_id = 10210, .name = "Quad" },
    .{ .file_id = 10211, .name = "Icosphere" },
    .{ .file_id = 10212, .name = "icosahedron" },
    .{ .file_id = 10213, .name = "pyramid" },
    .{ .file_id = 10401, .name = "EscToExit_back" },
    .{ .file_id = 10402, .name = "EscToExit_Text" },
    .{ .file_id = 10406, .name = "UnityWatermark-trial-big" },
    .{ .file_id = 10407, .name = "UnityWatermark-trial" },
    .{ .file_id = 10409, .name = "UnityWatermark-edu" },
    .{ .file_id = 10410, .name = "UnityWatermark-dev" },
    .{ .file_id = 10411, .name = "WarningSign" },
    .{ .file_id = 10413, .name = "UnityWatermark-proto" },
    .{ .file_id = 10755, .name = "Hidden/FrameDebuggerRenderTargetDisplay" },
    .{ .file_id = 10756, .name = "FrameDebuggerRenderTargetDisplay" },
    .{ .file_id = 11000, .name = "GameSkin" },
    .{ .file_id = 11001, .name = "box" },
    .{ .file_id = 11002, .name = "button active" },
    .{ .file_id = 11003, .name = "button hover" },
    .{ .file_id = 11004, .name = "button on hover" },
    .{ .file_id = 11005, .name = "button on" },
    .{ .file_id = 11006, .name = "button" },
    .{ .file_id = 11007, .name = "horizontal scrollbar thumb" },
    .{ .file_id = 11008, .name = "horizontal scrollbar" },
    .{ .file_id = 11009, .name = "horizontalslider" },
    .{ .file_id = 11010, .name = "slider thumb active" },
    .{ .file_id = 11011, .name = "slider thumb" },
    .{ .file_id = 11012, .name = "slidert humb hover" },
    .{ .file_id = 11013, .name = "toggle active" },
    .{ .file_id = 11014, .name = "toggle hover" },
    .{ .file_id = 11015, .name = "toggle on hover" },
    .{ .file_id = 11016, .name = "toggle on" },
    .{ .file_id = 11017, .name = "toggle on active" },
    .{ .file_id = 11018, .name = "toggle" },
    .{ .file_id = 11019, .name = "vertical scrollbar thumb" },
    .{ .file_id = 11020, .name = "vertical scrollbar" },
    .{ .file_id = 11021, .name = "verticalslider" },
    .{ .file_id = 11022, .name = "window on" },
    .{ .file_id = 11023, .name = "window" },
    .{ .file_id = 11024, .name = "textfield" },
    .{ .file_id = 11025, .name = "textfield on" },
    .{ .file_id = 11026, .name = "textfield hover" },
    .{ .file_id = 11993, .name = "TemplateAsset" },
    .{ .file_id = 11995, .name = "VisualTreeAsset" },
    .{ .file_id = 11998, .name = "StyleSheet" },
    .{ .file_id = 12001, .name = "GUISkin" },
    .{ .file_id = 12002, .name = "TerrainInspector" },
    .{ .file_id = 12003, .name = "ConsoleWindow" },
    .{ .file_id = 12004, .name = "ContainerWindow" },
    .{ .file_id = 12005, .name = "GUIView" },
    .{ .file_id = 12006, .name = "DockArea" },
    .{ .file_id = 12007, .name = "EditorWindow" },
    .{ .file_id = 12008, .name = "MainView" },
    .{ .file_id = 12009, .name = "PaneDragTab" },
    .{ .file_id = 12010, .name = "SplitView" },
    .{ .file_id = 12011, .name = "Toolbar" },
    .{ .file_id = 12012, .name = "Tools" },
    .{ .file_id = 12013, .name = "SceneView" },
    .{ .file_id = 12014, .name = "ProjectBrowser" },
    .{ .file_id = 12015, .name = "GameView" },
    .{ .file_id = 12016, .name = "PopupEditor" },
    .{ .file_id = 12017, .name = "ColorPicker" },
    .{ .file_id = 12018, .name = "AboutWindow" },
    .{ .file_id = 12019, .name = "InspectorWindow" },
    .{ .file_id = 12020, .name = "ShaderInspector" },
    .{ .file_id = 12024, .name = "AssetImporterEditor" },
    .{ .file_id = 12025, .name = "TextureImporterInspector" },
    .{ .file_id = 12027, .name = "TransformInspector" },
    .{ .file_id = 12028, .name = "ModelImporterEditor" },
    .{ .file_id = 12029, .name = "AudioImporterInspector" },
    .{ .file_id = 12030, .name = "TrueTypeFontImporterInspector" },
    .{ .file_id = 12031, .name = "TextureInspector" },
    .{ .file_id = 12032, .name = "GameObjectInspector" },
    .{ .file_id = 12033, .name = "MaterialEditor" },
    .{ .file_id = 12034, .name = "SaveWindowLayout" },
    .{ .file_id = 12035, .name = "DeleteWindowLayout" },
    .{ .file_id = 12036, .name = "RenderTextureInspector" },
    .{ .file_id = 12038, .name = "CubemapTextureInspector" },
    .{ .file_id = 12039, .name = "RagdollBuilder" },
    .{ .file_id = 12040, .name = "GenericInspector" },
    .{ .file_id = 12041, .name = "ProfilerIPWindow" },
    .{ .file_id = 12042, .name = "AppStatusBar" },
    .{ .file_id = 12043, .name = "BuildPlayerWindow" },
    .{ .file_id = 12044, .name = "PreferencesWindow" },
    .{ .file_id = 12045, .name = "Settings" },
    .{ .file_id = 12046, .name = "SnapSettings" },
    .{ .file_id = 12047, .name = "HostView" },
    .{ .file_id = 12048, .name = "TerrainWizard" },
    .{ .file_id = 12049, .name = "LightmapWizard" },
    .{ .file_id = 12050, .name = "ImportRawHeightmap" },
    .{ .file_id = 12051, .name = "ExportRawHeightmap" },
    .{ .file_id = 12052, .name = "SetResolutionWizard" },
    .{ .file_id = 12053, .name = "TreeWizard" },
    .{ .file_id = 12054, .name = "SplatWizard" },
    .{ .file_id = 12055, .name = "DetailMeshWizard" },
    .{ .file_id = 12056, .name = "DetailTextureWizard" },
    .{ .file_id = 12057, .name = "PlaceTreeWizard" },
    .{ .file_id = 12058, .name = "FlattenHeightmap" },
    .{ .file_id = 12059, .name = "FallbackEditorWindow" },
    .{ .file_id = 12060, .name = "MaximizedHostView" },
    .{ .file_id = 12061, .name = "SceneHierarchyWindow" },
    .{ .file_id = 12062, .name = "PackageExport" },
    .{ .file_id = 12063, .name = "PackageImport" },
    .{ .file_id = 12064, .name = "EyeDropper" },
    .{ .file_id = 12066, .name = "MonoScriptInspector" },
    .{ .file_id = 12067, .name = "AudioClipInspector" },
    .{ .file_id = 12068, .name = "ModelInspector" },
    .{ .file_id = 12069, .name = "TooltipView" },
    .{ .file_id = 12070, .name = "ProfilerWindow" },
    .{ .file_id = 12071, .name = "AnimationWindow" },
    .{ .file_id = 12073, .name = "AnimationEventPopup" },
    .{ .file_id = 12074, .name = "EditorSettingsInspector" },
    .{ .file_id = 12076, .name = "AnimationCleanupPopup" },
    .{ .file_id = 12077, .name = "ScriptReloadProperties" },
    .{ .file_id = 12078, .name = "MacroWindow" },
    .{ .file_id = 12079, .name = "LightingWindow" },
    .{ .file_id = 12080, .name = "AuxWindow" },
    .{ .file_id = 12081, .name = "ObjectSelector" },
    .{ .file_id = 12082, .name = "LabelCompletion" },
    .{ .file_id = 12083, .name = "CurveEditorWindow" },
    .{ .file_id = 12084, .name = "MonoScriptImporterInspector" },
    .{ .file_id = 12086, .name = "TextAssetInspector" },
    .{ .file_id = 12087, .name = "LightEditor" },
    .{ .file_id = 12088, .name = "AudioSourceInspector" },
    .{ .file_id = 12089, .name = "AudioLowPassFilterInspector" },
    .{ .file_id = 12090, .name = "OcclusionCullingWindow" },
    .{ .file_id = 12091, .name = "WebCamTextureInspector" },
    .{ .file_id = 12092, .name = "ShaderImporterInspector" },
    .{ .file_id = 12093, .name = "StandardShaderGUI" },
    .{ .file_id = 12094, .name = "LegacyIlluminShaderGUI" },
    .{ .file_id = 12095, .name = "GraphicsSettingsWindow" },
    .{ .file_id = 12096, .name = "PhysicsDebugWindow" },
    .{ .file_id = 12097, .name = "LightingExplorerWindow" },
    .{ .file_id = 12098, .name = "LightmapPreviewWindow" },
    .{ .file_id = 12099, .name = "AudioReverbZoneEditor" },
    .{ .file_id = 12101, .name = "ClothInspector" },
    .{ .file_id = 12103, .name = "PragmaFixingWindow" },
    .{ .file_id = 12104, .name = "WindInspector" },
    .{ .file_id = 12105, .name = "TreeEditor" },
    .{ .file_id = 12106, .name = "TreeData" },
    .{ .file_id = 12107, .name = "PlayerSettingsEditor" },
    .{ .file_id = 12108, .name = "EditorUpdateWindow" },
    .{ .file_id = 12109, .name = "AudioReverbFilterEditor" },
    .{ .file_id = 12111, .name = "AssetStoreWindow" },
    .{ .file_id = 12112, .name = "AssetStoreContext" },
    .{ .file_id = 12113, .name = "AssembleEditorSkin" },
    .{ .file_id = 12114, .name = "OcclusionAreaEditor" },
    .{ .file_id = 12115, .name = "CameraEditor" },
    .{ .file_id = 12116, .name = "WindowFocusState" },
    .{ .file_id = 12117, .name = "AndroidKeystoreWindow" },
    .{ .file_id = 12118, .name = "AudioDistortionFilterEditor" },
    .{ .file_id = 12119, .name = "AudioEchoFilterEditor" },
    .{ .file_id = 12120, .name = "AudioHighPassFilterEditor" },
    .{ .file_id = 12121, .name = "AudioChorusFilterEditor" },
    .{ .file_id = 12122, .name = "BoxColliderEditor" },
    .{ .file_id = 12123, .name = "SphereColliderEditor" },
    .{ .file_id = 12124, .name = "CapsuleColliderEditor" },
    .{ .file_id = 12125, .name = "MeshColliderEditor" },
    .{ .file_id = 12126, .name = "WheelColliderEditor" },
    .{ .file_id = 12127, .name = "RigidbodyEditor" },
    .{ .file_id = 12128, .name = "AssetSaveDialog" },
    .{ .file_id = 12129, .name = "AnnotationWindow" },
    .{ .file_id = 12130, .name = "IconSelector" },
    .{ .file_id = 12131, .name = "ScriptExecutionOrderInspector" },
    .{ .file_id = 12132, .name = "AnimationEditor" },
    .{ .file_id = 12133, .name = "SkinnedMeshRendererEditor" },
    .{ .file_id = 12134, .name = "PreviewWindow" },
    .{ .file_id = 12135, .name = "LODGroupEditor" },
    .{ .file_id = 12136, .name = "OffMeshLinkInspector" },
    .{ .file_id = 12137, .name = "ParticleSystemWindow" },
    .{ .file_id = 12138, .name = "ParticleSystemInspector" },
    .{ .file_id = 12139, .name = "MeshRendererEditor" },
    .{ .file_id = 12140, .name = "GradientPicker" },
    .{ .file_id = 12141, .name = "NavMeshEditorWindow" },
    .{ .file_id = 12142, .name = "FontInspector" },
    .{ .file_id = 12143, .name = "SpriteMaskEditor" },
    .{ .file_id = 12146, .name = "Brush" },
    .{ .file_id = 12147, .name = "BrushInspector" },
    .{ .file_id = 12148, .name = "TerrainLayerInspector" },
    .{ .file_id = 12149, .name = "TilemapRendererEditor" },
    .{ .file_id = 12150, .name = "SpriteRendererEditor" },
    .{ .file_id = 12151, .name = "SpriteInspector" },
    .{ .file_id = 12152, .name = "SpriteShapeRendererInspector" },
    .{ .file_id = 12153, .name = "TagManagerInspector" },
    .{ .file_id = 12154, .name = "RenderSettingsInspector" },
    .{ .file_id = 12155, .name = "ShaderVariantCollectionInspector" },
    .{ .file_id = 12160, .name = "AssemblyDefinitionImporterInspector" },
    .{ .file_id = 12161, .name = "AssemblyDefinitionAsset" },
    .{ .file_id = 12162, .name = "IHVImageFormatImporterInspector" },
    .{ .file_id = 12163, .name = "VideoClipImporterInspector" },
    .{ .file_id = 12164, .name = "SketchUpImporterEditor" },
    .{ .file_id = 12165, .name = "VideoClipImporterInspector/TargetSettings" },
    .{ .file_id = 12166, .name = "AudioImporterInspector/PlatformSettings" },
    .{ .file_id = 12167, .name = "ShaderImporterInspector/ShaderProperties" },
    .{ .file_id = 12168, .name = "AssemblyDefinitionReferenceImporterInspector/AssemblyDefinitionReferenceState" },
    .{ .file_id = 12169, .name = "AssemblyDefinitionImporterInspector/AssemblyDefinitionState" },
    .{ .file_id = 12170, .name = "AssemblyDefinitionReferenceImporterInspector" },
    .{ .file_id = 12171, .name = "AssemblyDefinitionReferenceAsset" },
    .{ .file_id = 12172, .name = "ComputeShaderImporterInspector" },
    .{ .file_id = 12173, .name = "TextScriptImporterEditor" },
    .{ .file_id = 12203, .name = "ProceduralTextureInspector" },
    .{ .file_id = 12204, .name = "NavMeshAgentInspector" },
    .{ .file_id = 12205, .name = "LightProbeGroupInspector" },
    .{ .file_id = 12206, .name = "LightProbeGroupSelection" },
    .{ .file_id = 12207, .name = "View" },
    .{ .file_id = 12208, .name = "OcclusionPortalInspector" },
    .{ .file_id = 12209, .name = "NavMeshObstacleInspector" },
    .{ .file_id = 12210, .name = "PopupList" },
    .{ .file_id = 12211, .name = "AssetStoreAssetInspector" },
    .{ .file_id = 12212, .name = "AssetStoreInstaBuyWindow" },
    .{ .file_id = 12213, .name = "AssetStoreLoginWindow" },
    .{ .file_id = 12214, .name = "LightProbesInspector" },
    .{ .file_id = 12215, .name = "AddComponentWindow" },
    .{ .file_id = 12216, .name = "EndNameEditAction" },
    .{ .file_id = 12217, .name = "DoCreateNoneAsset" },
    .{ .file_id = 12218, .name = "DoCreateNewAsset" },
    .{ .file_id = 12219, .name = "DoCreateFolder" },
    .{ .file_id = 12220, .name = "DoCreatePrefab" },
    .{ .file_id = 12221, .name = "DoCreateScriptAsset" },
    .{ .file_id = 12222, .name = "LicenseManagementWindow" },
    .{ .file_id = 12223, .name = "DoCreateAnimatorController" },
    .{ .file_id = 12226, .name = "LightmapParametersEditor" },
    .{ .file_id = 12227, .name = "DynamicCubemapEditor" },
    .{ .file_id = 12300, .name = "WindowResolve" },
    .{ .file_id = 12301, .name = "WindowChange" },
    .{ .file_id = 12303, .name = "WindowPending" },
    .{ .file_id = 12304, .name = "WindowRevert" },
    .{ .file_id = 12306, .name = "CharacterControllerEditor" },
    .{ .file_id = 12307, .name = "QualitySettingsEditor" },
    .{ .file_id = 12308, .name = "SavedSearchFilters" },
    .{ .file_id = 12310, .name = "TextMeshInspector" },
    .{ .file_id = 12311, .name = "Texture3DInspector" },
    .{ .file_id = 12312, .name = "MetroCreateTestCertificateWindow" },
    .{ .file_id = 12313, .name = "MetroCertificatePasswordWindow" },
    .{ .file_id = 12314, .name = "ModelImporterRigEditor" },
    .{ .file_id = 12315, .name = "ModelImporterModelEditor" },
    .{ .file_id = 12316, .name = "ModelImporterClipEditor" },
    .{ .file_id = 12317, .name = "ModelImporterMaterialEditor" },
    .{ .file_id = 12318, .name = "AvatarPreviewSelection" },
    .{ .file_id = 12319, .name = "PopupWindow" },
    .{ .file_id = 12320, .name = "PresetLibraryManager" },
    .{ .file_id = 12321, .name = "GradientPresetLibrary" },
    .{ .file_id = 12322, .name = "CurvePresetLibrary" },
    .{ .file_id = 12323, .name = "ColorPresetLibrary" },
    .{ .file_id = 12324, .name = "DoubleCurvePresetLibrary" },
    .{ .file_id = 12325, .name = "AtlasEditorWindow" },
    .{ .file_id = 12326, .name = "PackerWindow" },
    .{ .file_id = 12327, .name = "PolygonCollider2DEditor" },
    .{ .file_id = 12328, .name = "Physics2DPreferenceState" },
    .{ .file_id = 12329, .name = "Physics2DSettingsInspector" },
    .{ .file_id = 12330, .name = "GameViewSizes" },
    .{ .file_id = 12331, .name = "ColorPresetLibraryEditor" },
    .{ .file_id = 12332, .name = "GradientPresetLibraryEditor" },
    .{ .file_id = 12333, .name = "CurvePresetLibraryEditor" },
    .{ .file_id = 12334, .name = "DoubleCurvePresetLibraryEditor" },
    .{ .file_id = 12335, .name = "ReflectionProbeEditor" },
    .{ .file_id = 12336, .name = "LightProbeProxyVolumeEditor" },
    .{ .file_id = 12337, .name = "PrefabImporterEditor" },
    .{ .file_id = 12346, .name = "CustomCollider2DEditor" },
    .{ .file_id = 12347, .name = "CapsuleCollider2DEditor" },
    .{ .file_id = 12348, .name = "TargetJoint2DEditor" },
    .{ .file_id = 12349, .name = "RelativeJoint2DEditor" },
    .{ .file_id = 12350, .name = "BoxCollider2DEditor" },
    .{ .file_id = 12351, .name = "CircleCollider2DEditor" },
    .{ .file_id = 12352, .name = "EdgeCollider2DEditor" },
    .{ .file_id = 12353, .name = "AnchoredJoint2DEditor" },
    .{ .file_id = 12354, .name = "HingeJoint2DEditor" },
    .{ .file_id = 12355, .name = "SpringJoint2DEditor" },
    .{ .file_id = 12356, .name = "DistanceJoint2DEditor" },
    .{ .file_id = 12357, .name = "SliderJoint2DEditor" },
    .{ .file_id = 12358, .name = "WheelJoint2DEditor" },
    .{ .file_id = 12359, .name = "Effector2DEditor" },
    .{ .file_id = 12360, .name = "InterceptedEventsEditor" },
    .{ .file_id = 12361, .name = "RectTransformEditor" },
    .{ .file_id = 12362, .name = "SpriteEditorWindow" },
    .{ .file_id = 12363, .name = "SpriteAtlasInspector" },
    .{ .file_id = 12364, .name = "SpriteAtlasImporterInspector" },
    .{ .file_id = 12365, .name = "SpeedTreeImporterInspector" },
    .{ .file_id = 12366, .name = "SpeedTreeMaterialInspector" },
    .{ .file_id = 12367, .name = "BillboardRendererInspector" },
    .{ .file_id = 12368, .name = "BillboardAssetInspector" },
    .{ .file_id = 12369, .name = "SpeedTree8ShaderGUI" },
    .{ .file_id = 12372, .name = "AudioMixerEditor" },
    .{ .file_id = 12373, .name = "AudioMixerWindow" },
    .{ .file_id = 12374, .name = "AudioMixerGroupEditor" },
    .{ .file_id = 12375, .name = "AudioMixerControllerInspector" },
    .{ .file_id = 12376, .name = "AudioMixerSnapshotControllerInspector" },
    .{ .file_id = 12377, .name = "AudioContainerWindow" },
    .{ .file_id = 12378, .name = "AudioRandomContainerInspector" },
    .{ .file_id = 12380, .name = "Rigidbody2DEditor" },
    .{ .file_id = 12381, .name = "Joint2DEditor" },
    .{ .file_id = 12382, .name = "BuoyancyEffector2DEditor" },
    .{ .file_id = 12383, .name = "PlatformEffector2DEditor" },
    .{ .file_id = 12384, .name = "ScriptedImporterEditor" },
    .{ .file_id = 12385, .name = "StyleSheetImporter" },
    .{ .file_id = 12386, .name = "SerializableJsonDictionary" },
    .{ .file_id = 12387, .name = "StyleSheetImporterEditor" },
    .{ .file_id = 12388, .name = "ThemeStyleSheetImporter" },
    .{ .file_id = 12389, .name = "ThemeAssetDefinitionState" },
    .{ .file_id = 12390, .name = "ThemeStyleSheetImporterEditor" },
    .{ .file_id = 12391, .name = "GraphicsStateCollectionImporter" },
    .{ .file_id = 12394, .name = "GridEditor" },
    .{ .file_id = 12395, .name = "GridPalette" },
    .{ .file_id = 12396, .name = "Preset" },
    .{ .file_id = 12397, .name = "PresetEditor" },
    .{ .file_id = 12398, .name = "PresetManagerEditor" },
    .{ .file_id = 12399, .name = "PresetManager" },
    .{ .file_id = 12400, .name = "SceneSetEditor" },
    .{ .file_id = 12401, .name = "AssemblyDefinitionAsset" },
    .{ .file_id = 12402, .name = "ServicesEditorWindow" },
    .{ .file_id = 12405, .name = "SpeedTree9Importer" },
    .{ .file_id = 12406, .name = "SpeedTree9ImporterEditor" },
    .{ .file_id = 12407, .name = "SpeedTreeImporterOutputData" },
    .{ .file_id = 12408, .name = "SVGImporter" },
    .{ .file_id = 12500, .name = "GraphObject" },
    .{ .file_id = 12501, .name = "GraphObjectImp" },
    .{ .file_id = 12502, .name = "Holder" },
    .{ .file_id = 12503, .name = "UndoStateRecorder" },
    .{ .file_id = 12504, .name = "FieldWrapper" },
    .{ .file_id = 12505, .name = "GraphViewEditorWindow" },
    .{ .file_id = 12506, .name = "GraphViewEditorWindowImp" },
    .{ .file_id = 12507, .name = "ItemLibraryWindow" },
    .{ .file_id = 12901, .name = "AnimatorInspector" },
    .{ .file_id = 12902, .name = "AnimatorOverrideControllerInspector" },
    .{ .file_id = 12905, .name = "AnimationClipEditor" },
    .{ .file_id = 12906, .name = "AvatarEditor" },
    .{ .file_id = 12907, .name = "AnimatorTransitionInspector" },
    .{ .file_id = 12908, .name = "AnimatorStateTransitionInspector" },
    .{ .file_id = 12914, .name = "AnimatorControllerTool" },
    .{ .file_id = 12915, .name = "AvatarMaskInspector" },
    .{ .file_id = 12916, .name = "BlendTreeInspector" },
    .{ .file_id = 12917, .name = "AvatarMappingEditor" },
    .{ .file_id = 12918, .name = "AvatarMuscleEditor" },
    .{ .file_id = 12919, .name = "GraphGUI" },
    .{ .file_id = 12920, .name = "Graph" },
    .{ .file_id = 12921, .name = "Node" },
    .{ .file_id = 12925, .name = "PositionConstraintEditor" },
    .{ .file_id = 12926, .name = "RotationConstraintEditor" },
    .{ .file_id = 12927, .name = "ScaleConstraintEditor" },
    .{ .file_id = 12928, .name = "ParentConstraint" },
    .{ .file_id = 12929, .name = "AimConstraintEditor" },
    .{ .file_id = 12930, .name = "GraphGUI" },
    .{ .file_id = 12931, .name = "Graph" },
    .{ .file_id = 12932, .name = "StateNode" },
    .{ .file_id = 12933, .name = "AnyStateNode" },
    .{ .file_id = 12934, .name = "StateMachineNode" },
    .{ .file_id = 12935, .name = "StateEditor" },
    .{ .file_id = 12936, .name = "StateMachineInspector" },
    .{ .file_id = 12937, .name = "AnyStateNodeInspector" },
    .{ .file_id = 12938, .name = "EntryNodeInspector" },
    .{ .file_id = 12939, .name = "ExitNodeInspector" },
    .{ .file_id = 12940, .name = "StateMachineBehaviourEditor" },
    .{ .file_id = 12941, .name = "TimelineWindowViewPrefs" },
    .{ .file_id = 13001, .name = "EditorGameObjectCache" },
    .{ .file_id = 13138, .name = "Graph" },
    .{ .file_id = 13139, .name = "GraphInspector" },
    .{ .file_id = 13140, .name = "GraphGUI" },
    .{ .file_id = 13141, .name = "Node" },
    .{ .file_id = 13202, .name = "FrameDebuggerWindow" },
    .{ .file_id = 13203, .name = "PluginImporterInspector" },
    .{ .file_id = 13205, .name = "ParameterControllerEditor" },
    .{ .file_id = 13312, .name = "Tile" },
    .{ .file_id = 13313, .name = "TileBase" },
    .{ .file_id = 13401, .name = "TestRunnerWindow" },
    .{ .file_id = 13501, .name = "GUIViewDebuggerWindow" },
    .{ .file_id = 13510, .name = "VisualEffectInspector" },
    .{ .file_id = 13601, .name = "LookDevView" },
    .{ .file_id = 13602, .name = "LookDevConfig" },
    .{ .file_id = 13603, .name = "LookDevEnvironmentLibrary" },
    .{ .file_id = 13604, .name = "VideoPlayerEditor" },
    .{ .file_id = 13800, .name = "WebGLStrippingInfo" },
    .{ .file_id = 13802, .name = "StrippingInfo" },
    .{ .file_id = 13803, .name = "AndroidBuildProperties" },
    .{ .file_id = 13804, .name = "UIElementsViewImporter" },
    .{ .file_id = 13805, .name = "DefaultBuildProperties" },
    .{ .file_id = 13806, .name = "GraphViewUndoRedoSelection" },
    .{ .file_id = 13807, .name = "UIElementsSnippetAsset" },
    .{ .file_id = 13852, .name = "StreamingControllerEditor" },
    .{ .file_id = 13853, .name = "SettingsWindow" },
    .{ .file_id = 13854, .name = "ProjectSettingsWindow" },
    .{ .file_id = 13855, .name = "PreferenceSettingsWindow" },
    .{ .file_id = 13856, .name = "GraphViewMinimapWindow" },
    .{ .file_id = 13857, .name = "GraphViewBlackboardWindow" },
    .{ .file_id = 13900, .name = "AnimationWindowKeySelection" },
    .{ .file_id = 13901, .name = "AnimationWindowSelectionItem" },
    .{ .file_id = 13902, .name = "GameObjectSelectionItem" },
    .{ .file_id = 13903, .name = "AnimationClipSelectionItem" },
    .{ .file_id = 13904, .name = "CurveEditorSelection" },
    .{ .file_id = 13951, .name = "ShortcutManagerWindow" },
    .{ .file_id = 13952, .name = "PackageManifestImporterEditor" },
    .{ .file_id = 13953, .name = "PackageManagerWindow" },
    .{ .file_id = 13954, .name = "EditorSnapSettingsData" },
    .{ .file_id = 13955, .name = "ModeDescriptor" },
    .{ .file_id = 13956, .name = "UIElementsDebugger" },
    .{ .file_id = 13957, .name = "UIElementsEventsDebugger" },
    .{ .file_id = 13958, .name = "PackageManifestImporterEditor/PackageManifestState" },
    .{ .file_id = 13959, .name = "SnapSettingsWindow" },
    .{ .file_id = 13960, .name = "ProgressWindow" },
    .{ .file_id = 13961, .name = "PropertyEditor" },
    .{ .file_id = 13962, .name = "EditorToolbar" },
    .{ .file_id = 13964, .name = "PackageManagerProjectSettings" },
    .{ .file_id = 13965, .name = "EditorToolWindow" },
    .{ .file_id = 13966, .name = "SceneTemplateAsset" },
    .{ .file_id = 13967, .name = "SceneTemplateAssetInspectorWindow" },
    .{ .file_id = 13968, .name = "UIElementsSamples" },
    .{ .file_id = 13969, .name = "PanelSettingsInspector" },
    .{ .file_id = 13970, .name = "DeviceInfoImporterEditor" },
    .{ .file_id = 13971, .name = "DeviceInfoAssetEditor" },
    .{ .file_id = 13972, .name = "DeviceInfoAsset" },
    .{ .file_id = 13973, .name = "DeviceInfoImporter" },
    .{ .file_id = 13974, .name = "SimulatorWindow" },
    .{ .file_id = 13975, .name = "UIDocumentInspector" },
    .{ .file_id = 13976, .name = "UIRendererEditor" },
    .{ .file_id = 13980, .name = "SearchDatabase" },
    .{ .file_id = 13981, .name = "SearchDatabaseImporter" },
    .{ .file_id = 13982, .name = "SearchQueryAsset" },
    .{ .file_id = 13984, .name = "SearchWindow" },
    .{ .file_id = 13986, .name = "IndexManager" },
    .{ .file_id = 13987, .name = "MainToolbarWindow" },
    .{ .file_id = 13988, .name = "OverlayPreset" },
    .{ .file_id = 13989, .name = "OverlayPresetManager" },
    .{ .file_id = 13990, .name = "ManipulationToolCustomEditor" },
    .{ .file_id = 13991, .name = "SearchPickerWindow" },
    .{ .file_id = 13993, .name = "GameObjectToolContextCustomEditor" },
    .{ .file_id = 13999, .name = "Builder" },
    .{ .file_id = 14000, .name = "UndoHistoryWindow" },
    .{ .file_id = 14001, .name = "ParticleSystemForceFieldInspector" },
    .{ .file_id = 14002, .name = "HierarchyWindow" },
    .{ .file_id = 14003, .name = "AccessibilityHierarchyViewerWindow" },
    .{ .file_id = 15000, .name = "EditorTextSettings" },
    .{ .file_id = 15001, .name = "UILayoutDebuggerWindow" },
    .{ .file_id = 15002, .name = "AllocatorDebugger" },
    .{ .file_id = 15003, .name = "BuildProfile" },
    .{ .file_id = 15004, .name = "BuildProfileWindow" },
    .{ .file_id = 15005, .name = "BuildProfileContext" },
    .{ .file_id = 15006, .name = "PlatformDiscoveryWindow" },
    .{ .file_id = 15007, .name = "OverlayCanvasesData" },
    .{ .file_id = 15008, .name = "EditorToolsSettingsData" },
    .{ .file_id = 15009, .name = "BuildProfileGraphicsSettings" },
    .{ .file_id = 15010, .name = "BuildProfileQualitySettings" },
    .{ .file_id = 15011, .name = "GridSettings" },
    .{ .file_id = 15012, .name = "BuildAutomationSettings" },
    .{ .file_id = 15020, .name = "TopView" },
    .{ .file_id = 15021, .name = "DeployData" },
    .{ .file_id = 15022, .name = "MultiplayerRoleData" },
    .{ .file_id = 15023, .name = "MultiplayerRolesSettings" },
    .{ .file_id = 15024, .name = "OrchestratedScenario" },
    .{ .file_id = 15025, .name = "MultiplayerWindow" },
    .{ .file_id = 15027, .name = "OrchestratedScenarioUserSettings" },
    .{ .file_id = 15050, .name = "PlayModeUserSettings" },
    .{ .file_id = 15051, .name = "PlayModeScenariosWindow" },
    .{ .file_id = 15052, .name = "ActiveScenarioWindow" },
    .{ .file_id = 15134, .name = "BuilderInspectorPreviewWindow" },
    .{ .file_id = 15135, .name = "UIToolkitProjectSettings" },
    .{ .file_id = 15136, .name = "StyleSheetsWindow" },
    .{ .file_id = 15800, .name = "ContentDirectoryProfile" },
    .{ .file_id = 19000, .name = "TextSettings" },
    .{ .file_id = 19001, .name = "FontAsset" },
    .{ .file_id = 19002, .name = "SpriteAsset" },
    .{ .file_id = 19003, .name = "TextColorGradient" },
    .{ .file_id = 19004, .name = "TextStyleSheet" },
    .{ .file_id = 19100, .name = "VectorImage" },
    .{ .file_id = 19101, .name = "PanelSettings" },
    .{ .file_id = 19102, .name = "UIDocument" },
    .{ .file_id = 19103, .name = "PanelTextSettings" },
    .{ .file_id = 19104, .name = "UIRenderer" },
    .{ .file_id = 19106, .name = "PanelInputConfiguration" },
    .{ .file_id = 19107, .name = "FilterFunctionDefinition" },
    .{ .file_id = 19202, .name = "ThemeStyleSheet" },
    .{ .file_id = 19300, .name = "PhysicsLowLevelSettings2D" },
    .{ .file_id = 19301, .name = "PhysicsCoreSettings2D" },
    .{ .file_id = 21000, .name = "AdaptivePerformanceGeneralSettings" },
    .{ .file_id = 21001, .name = "AdaptivePerformanceManagerSettings" },
    .{ .file_id = 21002, .name = "AdaptivePerformanceLoader" },
    .{ .file_id = 21003, .name = "AdaptivePerformanceLoaderHelper" },
    .{ .file_id = 21004, .name = "AdaptivePerformanceManagerSpawner" },
    .{ .file_id = 21005, .name = "AdaptivePerformanceScaler" },
    .{ .file_id = 21006, .name = "IAdaptivePerformanceSettings" },
    .{ .file_id = 21007, .name = "BasicProviderLoader" },
    .{ .file_id = 21008, .name = "BasicProviderSettings" },
    .{ .file_id = 21010, .name = "AdaptivePerformanceGeneralSettingsPerBuildTarget" },
    .{ .file_id = 21011, .name = "SimulatorProviderLoader" },
    .{ .file_id = 21012, .name = "SimulatorProviderSettings" },
    .{ .file_id = 21013, .name = "BuildProfileProviderContainer" },
    .{ .file_id = 21014, .name = "Switch2PlayerSettings" },
    .{ .file_id = 21015, .name = "ProjectAuditorWindow" },
};

const builtin_extra = [_]Entry{
    .{ .file_id = 1, .name = "Legacy Shaders/Diffuse Fast" },
    .{ .file_id = 2, .name = "Legacy Shaders/Bumped Diffuse" },
    .{ .file_id = 3, .name = "Legacy Shaders/Specular" },
    .{ .file_id = 4, .name = "Legacy Shaders/Bumped Specular" },
    .{ .file_id = 5, .name = "Legacy Shaders/Diffuse Detail" },
    .{ .file_id = 6, .name = "Legacy Shaders/VertexLit" },
    .{ .file_id = 7, .name = "Legacy Shaders/Diffuse" },
    .{ .file_id = 8, .name = "Legacy Shaders/Parallax Diffuse" },
    .{ .file_id = 9, .name = "Legacy Shaders/Parallax Specular" },
    .{ .file_id = 10, .name = "Legacy Shaders/Self-Illumin/Diffuse" },
    .{ .file_id = 11, .name = "Legacy Shaders/Self-Illumin/Bumped Diffuse" },
    .{ .file_id = 12, .name = "Legacy Shaders/Self-Illumin/Specular" },
    .{ .file_id = 13, .name = "Legacy Shaders/Self-Illumin/Bumped Specular" },
    .{ .file_id = 14, .name = "Legacy Shaders/Self-Illumin/VertexLit" },
    .{ .file_id = 15, .name = "Legacy Shaders/Self-Illumin/Parallax Diffuse" },
    .{ .file_id = 16, .name = "Legacy Shaders/Self-Illumin/Parallax Specular" },
    .{ .file_id = 19, .name = "Hidden/Internal-StencilWrite" },
    .{ .file_id = 20, .name = "Legacy Shaders/Reflective/Diffuse" },
    .{ .file_id = 21, .name = "Legacy Shaders/Reflective/Bumped Diffuse" },
    .{ .file_id = 22, .name = "Legacy Shaders/Reflective/Specular" },
    .{ .file_id = 23, .name = "Legacy Shaders/Reflective/Bumped Specular" },
    .{ .file_id = 24, .name = "Legacy Shaders/Reflective/VertexLit" },
    .{ .file_id = 25, .name = "Legacy Shaders/Reflective/Bumped Unlit" },
    .{ .file_id = 26, .name = "Legacy Shaders/Reflective/Bumped VertexLit" },
    .{ .file_id = 27, .name = "Legacy Shaders/Reflective/Parallax Diffuse" },
    .{ .file_id = 28, .name = "Legacy Shaders/Reflective/Parallax Specular" },
    .{ .file_id = 30, .name = "Legacy Shaders/Transparent/Diffuse" },
    .{ .file_id = 31, .name = "Legacy Shaders/Transparent/Bumped Diffuse" },
    .{ .file_id = 32, .name = "Legacy Shaders/Transparent/Specular" },
    .{ .file_id = 33, .name = "Legacy Shaders/Transparent/Bumped Specular" },
    .{ .file_id = 34, .name = "Legacy Shaders/Transparent/VertexLit" },
    .{ .file_id = 35, .name = "Legacy Shaders/Transparent/Parallax Diffuse" },
    .{ .file_id = 36, .name = "Legacy Shaders/Transparent/Parallax Specular" },
    .{ .file_id = 40, .name = "Legacy Shaders/Lightmapped/VertexLit" },
    .{ .file_id = 41, .name = "Legacy Shaders/Lightmapped/Diffuse" },
    .{ .file_id = 42, .name = "Legacy Shaders/Lightmapped/Bumped Diffuse" },
    .{ .file_id = 43, .name = "Legacy Shaders/Lightmapped/Specular" },
    .{ .file_id = 44, .name = "Legacy Shaders/Lightmapped/Bumped Specular" },
    .{ .file_id = 45, .name = "Standard (Specular setup)" },
    .{ .file_id = 46, .name = "Standard" },
    .{ .file_id = 47, .name = "Autodesk Interactive" },
    .{ .file_id = 50, .name = "Legacy Shaders/Transparent/Cutout/VertexLit" },
    .{ .file_id = 51, .name = "Legacy Shaders/Transparent/Cutout/Diffuse" },
    .{ .file_id = 52, .name = "Legacy Shaders/Transparent/Cutout/Bumped Diffuse" },
    .{ .file_id = 53, .name = "Legacy Shaders/Transparent/Cutout/Specular" },
    .{ .file_id = 54, .name = "Legacy Shaders/Transparent/Cutout/Bumped Specular" },
    .{ .file_id = 62, .name = "Hidden/Internal-DepthNormalsTexture" },
    .{ .file_id = 64, .name = "Hidden/Internal-ScreenSpaceShadows" },
    .{ .file_id = 65, .name = "Hidden/Internal-CombineDepthNormals" },
    .{ .file_id = 66, .name = "Hidden/BlitCopy" },
    .{ .file_id = 67, .name = "Hidden/BlitCopyDepth" },
    .{ .file_id = 68, .name = "Hidden/ConvertTexture" },
    .{ .file_id = 69, .name = "Hidden/Internal-DeferredShading" },
    .{ .file_id = 74, .name = "Hidden/Internal-DeferredReflections" },
    .{ .file_id = 75, .name = "Hidden/Internal-MotionVectors" },
    .{ .file_id = 100, .name = "Legacy Shaders/Decal" },
    .{ .file_id = 101, .name = "FX/Flare" },
    .{ .file_id = 102, .name = "Hidden/Internal-Flare" },
    .{ .file_id = 103, .name = "Skybox/Cubemap" },
    .{ .file_id = 104, .name = "Skybox/6 Sided" },
    .{ .file_id = 105, .name = "Hidden/Internal-Halo" },
    .{ .file_id = 106, .name = "Skybox/Procedural" },
    .{ .file_id = 107, .name = "Hidden/BlitCopyWithDepth" },
    .{ .file_id = 108, .name = "Skybox/Panoramic" },
    .{ .file_id = 109, .name = "Hidden/BlitToDepth" },
    .{ .file_id = 110, .name = "Hidden/BlitToDepth_MSAA" },
    .{ .file_id = 111, .name = "Hidden/BlitCopyHDRTonemap" },
    .{ .file_id = 112, .name = "Hidden/BlitCopyHDRTonemappedToHDRTonemap" },
    .{ .file_id = 113, .name = "Hidden/Internal-DebugPattern" },
    .{ .file_id = 114, .name = "Hidden/BlitCopyHDRTonemappedToSDR" },
    .{ .file_id = 200, .name = "Legacy Shaders/Particles/Additive" },
    .{ .file_id = 201, .name = "Legacy Shaders/Particles/~Additive-Multiply" },
    .{ .file_id = 202, .name = "Legacy Shaders/Particles/Additive (Soft)" },
    .{ .file_id = 203, .name = "Legacy Shaders/Particles/Alpha Blended" },
    .{ .file_id = 205, .name = "Legacy Shaders/Particles/Multiply" },
    .{ .file_id = 206, .name = "Legacy Shaders/Particles/Multiply (Double)" },
    .{ .file_id = 207, .name = "Legacy Shaders/Particles/Alpha Blended Premultiply" },
    .{ .file_id = 208, .name = "Legacy Shaders/Particles/VertexLit Blended" },
    .{ .file_id = 209, .name = "Legacy Shaders/Particles/Anim Alpha Blended" },
    .{ .file_id = 210, .name = "Particles/Standard Surface" },
    .{ .file_id = 211, .name = "Particles/Standard Unlit" },
    .{ .file_id = 9000, .name = "Hidden/Internal-GUITextureClip" },
    .{ .file_id = 9001, .name = "Hidden/Internal-GUITextureClipText" },
    .{ .file_id = 9002, .name = "Hidden/Internal-GUITexture" },
    .{ .file_id = 9003, .name = "Hidden/Internal-GUITextureBlit" },
    .{ .file_id = 9004, .name = "Hidden/Internal-GUIRoundedRect" },
    .{ .file_id = 9007, .name = "Hidden/Internal-GUIRoundedRectWithColorPerBorder" },
    .{ .file_id = 9100, .name = "Hidden/Internal-UIRDefault" },
    .{ .file_id = 9101, .name = "Hidden/Internal-UIRAtlasBlitCopy" },
    .{ .file_id = 9105, .name = "Hidden/Internal-UIE-ColorConversionBlit" },
    .{ .file_id = 10300, .name = "Default-Particle" },
    .{ .file_id = 10301, .name = "Default-Particle" },
    .{ .file_id = 10302, .name = "Default-Diffuse" },
    .{ .file_id = 10303, .name = "Default-Material" },
    .{ .file_id = 10304, .name = "Default-Skybox" },
    .{ .file_id = 10305, .name = "Default-Checker" },
    .{ .file_id = 10306, .name = "Default-Line" },
    .{ .file_id = 10307, .name = "Default-ParticleSystem" },
    .{ .file_id = 10308, .name = "Default-ParticleSystem" },
    .{ .file_id = 10309, .name = "Default-Checker-Gray" },
    .{ .file_id = 10403, .name = "UnitySplash-Light" },
    .{ .file_id = 10404, .name = "UnitySplash-Light" },
    .{ .file_id = 10490, .name = "Hidden/Nature/Terrain/Utilities" },
    .{ .file_id = 10500, .name = "Hidden/TerrainEngine/Details/Vertexlit" },
    .{ .file_id = 10501, .name = "Hidden/TerrainEngine/Details/WavingDoublePass" },
    .{ .file_id = 10502, .name = "Hidden/TerrainEngine/Details/BillboardWavingDoublePass" },
    .{ .file_id = 10503, .name = "Hidden/TerrainEngine/Splatmap/Diffuse-AddPass" },
    .{ .file_id = 10504, .name = "Hidden/TerrainEngine/Splatmap/Diffuse-Base" },
    .{ .file_id = 10505, .name = "Nature/Terrain/Diffuse" },
    .{ .file_id = 10506, .name = "Hidden/TerrainEngine/Splatmap/Diffuse-BaseGen" },
    .{ .file_id = 10507, .name = "Hidden/TerrainEngine/BillboardTree" },
    .{ .file_id = 10508, .name = "Hidden/Nature/Tree Soft Occlusion Bark Rendertex" },
    .{ .file_id = 10509, .name = "Nature/Tree Soft Occlusion Bark" },
    .{ .file_id = 10510, .name = "Hidden/Nature/Tree Soft Occlusion Leaves Rendertex" },
    .{ .file_id = 10511, .name = "Nature/Tree Soft Occlusion Leaves" },
    .{ .file_id = 10512, .name = "Legacy Shaders/Transparent/Cutout/Soft Edge Unlit" },
    .{ .file_id = 10513, .name = "Hidden/TerrainEngine/CameraFacingBillboardTree" },
    .{ .file_id = 10600, .name = "Nature/Tree Creator Bark" },
    .{ .file_id = 10601, .name = "Nature/Tree Creator Leaves" },
    .{ .file_id = 10602, .name = "Hidden/Nature/Tree Creator Bark Rendertex" },
    .{ .file_id = 10603, .name = "Hidden/Nature/Tree Creator Leaves Rendertex" },
    .{ .file_id = 10604, .name = "Hidden/Nature/Tree Creator Bark Optimized" },
    .{ .file_id = 10605, .name = "Hidden/Nature/Tree Creator Leaves Optimized" },
    .{ .file_id = 10606, .name = "Nature/Tree Creator Leaves Fast" },
    .{ .file_id = 10607, .name = "Hidden/Nature/Tree Creator Leaves Fast Optimized" },
    .{ .file_id = 10608, .name = "Hidden/Nature/Tree Creator Albedo Rendertex" },
    .{ .file_id = 10609, .name = "Hidden/Nature/Tree Creator Normal Rendertex" },
    .{ .file_id = 10620, .name = "Nature/Terrain/Specular" },
    .{ .file_id = 10621, .name = "Hidden/TerrainEngine/Splatmap/Specular-AddPass" },
    .{ .file_id = 10622, .name = "Hidden/TerrainEngine/Splatmap/Specular-Base" },
    .{ .file_id = 10623, .name = "Nature/Terrain/Standard" },
    .{ .file_id = 10624, .name = "Hidden/TerrainEngine/Splatmap/Standard-AddPass" },
    .{ .file_id = 10625, .name = "Hidden/TerrainEngine/Splatmap/Standard-Base" },
    .{ .file_id = 10626, .name = "Hidden/TerrainEngine/Splatmap/Standard-BaseGen" },
    .{ .file_id = 10650, .name = "Default-Terrain-Diffuse" },
    .{ .file_id = 10651, .name = "Default-Terrain-Specular" },
    .{ .file_id = 10652, .name = "Default-Terrain-Standard" },
    .{ .file_id = 10700, .name = "Mobile/Skybox" },
    .{ .file_id = 10701, .name = "Mobile/VertexLit" },
    .{ .file_id = 10703, .name = "Mobile/Diffuse" },
    .{ .file_id = 10704, .name = "Mobile/Bumped Diffuse" },
    .{ .file_id = 10705, .name = "Mobile/Bumped Specular" },
    .{ .file_id = 10706, .name = "Mobile/Bumped Specular (1 Directional Realtime Light)" },
    .{ .file_id = 10707, .name = "Mobile/VertexLit (Only Directional Lights)" },
    .{ .file_id = 10708, .name = "Mobile/Unlit (Supports Lightmap)" },
    .{ .file_id = 10720, .name = "Mobile/Particles/Additive" },
    .{ .file_id = 10721, .name = "Mobile/Particles/Alpha Blended" },
    .{ .file_id = 10722, .name = "Mobile/Particles/VertexLit Blended" },
    .{ .file_id = 10723, .name = "Mobile/Particles/Multiply" },
    .{ .file_id = 10750, .name = "Unlit/Transparent" },
    .{ .file_id = 10751, .name = "Unlit/Transparent Cutout" },
    .{ .file_id = 10752, .name = "Unlit/Texture" },
    .{ .file_id = 10753, .name = "Sprites/Default" },
    .{ .file_id = 10754, .name = "Sprites-Default" },
    .{ .file_id = 10755, .name = "Unlit/Color" },
    .{ .file_id = 10757, .name = "Sprites/Mask" },
    .{ .file_id = 10758, .name = "Sprites-Mask" },
    .{ .file_id = 10760, .name = "UI/Unlit/Transparent" },
    .{ .file_id = 10761, .name = "UI/Unlit/Detail" },
    .{ .file_id = 10762, .name = "UI/Unlit/Text" },
    .{ .file_id = 10763, .name = "UI/Unlit/Text Detail" },
    .{ .file_id = 10764, .name = "UI/Lit/Transparent" },
    .{ .file_id = 10765, .name = "UI/Lit/Bumped" },
    .{ .file_id = 10766, .name = "UI/Lit/Detail" },
    .{ .file_id = 10767, .name = "UI/Lit/Refraction" },
    .{ .file_id = 10768, .name = "UI/Lit/Refraction Detail" },
    .{ .file_id = 10770, .name = "UI/Default" },
    .{ .file_id = 10782, .name = "UI/Default Font" },
    .{ .file_id = 10783, .name = "UI/DefaultETC1" },
    .{ .file_id = 10784, .name = "Hidden/UI/CompositeOverdraw" },
    .{ .file_id = 10785, .name = "Hidden/UI/Overdraw" },
    .{ .file_id = 10800, .name = "Sprites/Diffuse" },
    .{ .file_id = 10900, .name = "Checkmark" },
    .{ .file_id = 10901, .name = "Checkmark" },
    .{ .file_id = 10904, .name = "UISprite" },
    .{ .file_id = 10905, .name = "UISprite" },
    .{ .file_id = 10906, .name = "Background" },
    .{ .file_id = 10907, .name = "Background" },
    .{ .file_id = 10910, .name = "InputFieldBackground" },
    .{ .file_id = 10911, .name = "InputFieldBackground" },
    .{ .file_id = 10912, .name = "Knob" },
    .{ .file_id = 10913, .name = "Knob" },
    .{ .file_id = 10914, .name = "DropdownArrow" },
    .{ .file_id = 10915, .name = "DropdownArrow" },
    .{ .file_id = 10916, .name = "UIMask" },
    .{ .file_id = 10917, .name = "UIMask" },
    .{ .file_id = 13000, .name = "Hidden/VisualizeShadingRateImage" },
    .{ .file_id = 14000, .name = "Nature/SpeedTree" },
    .{ .file_id = 14001, .name = "Nature/SpeedTree Billboard" },
    .{ .file_id = 14002, .name = "Nature/SpeedTree8" },
    .{ .file_id = 14003, .name = "Nature/SpeedTree9" },
    .{ .file_id = 15100, .name = "Hidden/GIDebug/TextureUV" },
    .{ .file_id = 15101, .name = "Hidden/GIDebug/ShowLightMask" },
    .{ .file_id = 15102, .name = "Hidden/GIDebug/UV1sAsPositions" },
    .{ .file_id = 15103, .name = "Hidden/GIDebug/VertexColors" },
    .{ .file_id = 15104, .name = "Hidden/CubeBlur" },
    .{ .file_id = 15105, .name = "Hidden/CubeCopy" },
    .{ .file_id = 15106, .name = "Hidden/CubeBlend" },
    .{ .file_id = 15200, .name = "Default-HighResolution" },
    .{ .file_id = 15201, .name = "Default-LowResolution" },
    .{ .file_id = 15203, .name = "Default-VeryLowResolution" },
    .{ .file_id = 15204, .name = "Default-Medium" },
    .{ .file_id = 15300, .name = "VR/SpatialMapping/Occlusion" },
    .{ .file_id = 15301, .name = "VR/SpatialMapping/Wireframe" },
    .{ .file_id = 15302, .name = "SpatialMappingOcclusion" },
    .{ .file_id = 15303, .name = "SpatialMappingWireframe" },
    .{ .file_id = 15304, .name = "Hidden/VR/BlitTexArraySlice" },
    .{ .file_id = 15305, .name = "Hidden/VR/Internal-VRDistortion" },
    .{ .file_id = 15306, .name = "Hidden/VR/BlitTexArraySliceToDepth" },
    .{ .file_id = 15307, .name = "Hidden/VR/BlitTexArraySliceToDepth_MSAA" },
    .{ .file_id = 15308, .name = "Hidden/Internal-ODSWorldTexture" },
    .{ .file_id = 15309, .name = "Hidden/Internal-CubemapToEquirect" },
    .{ .file_id = 15312, .name = "Hidden/VR/BlitFromTex2DToTexArraySlice" },
    .{ .file_id = 15313, .name = "Hidden/VR/BlitCopyHDRTonemapTexArraySlice" },
    .{ .file_id = 15314, .name = "Hidden/VR/BlitCopyHDRTonemappedToHDRTonemapTexArraySlice" },
    .{ .file_id = 15315, .name = "Hidden/VR/BlitCopyHDRTonemappedToSDRTexArraySlice" },
    .{ .file_id = 16000, .name = "Hidden/VideoComposite" },
    .{ .file_id = 16001, .name = "Hidden/VideoDecode" },
    .{ .file_id = 16002, .name = "Hidden/VideoDecodeOSX" },
    .{ .file_id = 16003, .name = "Hidden/VideoDecodeAndroid" },
    .{ .file_id = 17000, .name = "Hidden/Compositing" },
    .{ .file_id = 18000, .name = "Hidden/TerrainEngine/PaintHeight" },
    .{ .file_id = 18001, .name = "Hidden/TerrainEngine/HeightBlitCopy" },
    .{ .file_id = 18002, .name = "Hidden/TerrainEngine/GenerateNormalmap" },
    .{ .file_id = 18003, .name = "Hidden/TerrainEngine/TerrainLayerUtils" },
    .{ .file_id = 18004, .name = "Hidden/TerrainEngine/BrushPreview" },
    .{ .file_id = 18005, .name = "Hidden/TerrainEngine/CrossBlendNeighbors" },
    .{ .file_id = 18006, .name = "Hidden/TerrainEngine/TerrainBlitCopyZWrite" },
    .{ .file_id = 19010, .name = "Hidden/TextCore/Distance Field" },
    .{ .file_id = 19011, .name = "Hidden/TextCore/Distance Field SSD" },
    .{ .file_id = 19012, .name = "Hidden/TextCore/Sprite" },
    .{ .file_id = 20000, .name = "UnitySplash-Dark" },
    .{ .file_id = 20001, .name = "UnitySplash-Dark" },
    .{ .file_id = 20100, .name = "Invalidated" },
    .{ .file_id = 20200, .name = "Default-Skybox-Cubemap" },
    .{ .file_id = 20201, .name = "LightingData" },
    .{ .file_id = 20204, .name = "icudt73l" },
    .{ .file_id = 20300, .name = "Hidden/UIR/GaussianBlur" },
    .{ .file_id = 20301, .name = "Hidden/UIR/ColorEffect" },
    .{ .file_id = 20400, .name = "Hidden/VectorGraphics/Vector" },
    .{ .file_id = 20401, .name = "Hidden/VectorGraphics/VectorGradient" },
    .{ .file_id = 20402, .name = "Hidden/VectorGraphics/VectorBlendMax" },
    .{ .file_id = 20403, .name = "Hidden/VectorGraphics/VectorDemultiply" },
    .{ .file_id = 20404, .name = "Hidden/VectorGraphics/VectorExpandEdges" },
    .{ .file_id = 20410, .name = "Internal-VectorGraphics-Vector" },
    .{ .file_id = 20411, .name = "Internal-VectorGraphics-VectorGradient" },
    .{ .file_id = 20500, .name = "Hidden/Physics2D/SDF_CircleGeometry" },
    .{ .file_id = 20501, .name = "Hidden/Physics2D/SDF_CapsuleGeometry" },
    .{ .file_id = 20502, .name = "Hidden/Physics2D/SDF_PolygonGeometry" },
    .{ .file_id = 20506, .name = "Hidden/Physics2D/SDF_Line" },
    .{ .file_id = 20507, .name = "Hidden/Physics2D/SDF_Point" },
    .{ .file_id = 20510, .name = "SDF_CircleGeometry" },
    .{ .file_id = 20511, .name = "SDF_CapsuleGeometry" },
    .{ .file_id = 20512, .name = "SDF_PolygonGeometry" },
    .{ .file_id = 20516, .name = "SDF_Line" },
    .{ .file_id = 20517, .name = "SDF_Point" },
};
